// angular/agence-voyage/src/app/components/admin-utilisateur-reservations/admin-utilisateur-reservations.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ReservationService } from '../../services/reservation.service';
import { VoyageService } from '../../services/voyage.service';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../services/auth.service';
import { ServeurService } from '../../services/serveur.service';

@Component({
  selector: 'app-admin-utilisateur-reservations',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-utilisateur-reservations.component.html',
  styleUrls: ['../admin-voyages/admin-voyages.component.css']
})
export class AdminUtilisateurReservationsComponent implements OnInit {
  private reservationService = inject(ReservationService);
  private voyageService = inject(VoyageService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private cdr = inject(ChangeDetectorRef);
  private http = inject(HttpClient);
  private authService = inject(AuthService);
  private serveurService = inject(ServeurService);

  utilisateurId!: number;
  reservations: any[] = [];
  isLoading = true;

  // 👉 GESTION DE L'ÉCHANGE
  reservationAEchanger: any = null;
  voyagesDisponibles: any[] = [];
  
  // 👉 FILTRES POUR LE CATALOGUE D'ÉCHANGE
  filtreDepart: string = '';
  filtreArrivee: string = '';
  filtreDate: string = '';
  texteRecherche: string = '';
  
  // 👉 NOUVEAU : Filtre manuel des places
  filtrePlaces: number | null = null;

  ngOnInit() {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.utilisateurId = Number(idParam);
      this.chargerDonnees();
    }
  }

  chargerDonnees() {
    this.isLoading = true;
    this.reservationService.getHistoriqueUtilisateur(this.utilisateurId).subscribe({
      next: (data: any) => {
        const donneesBrutes = data?.results || data?.content || data?._embedded?.reservations || data;
        this.reservations = Array.isArray(donneesBrutes) ? donneesBrutes : [];
        this.isLoading = false;
        this.cdr.detectChanges();
      },
      error: () => {
        this.reservations = [];
        this.isLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  annulerReservation(id: number) {
    if (confirm("🚨 Voulez-vous vraiment annuler ce billet et rembourser le client ?")) {
       this.reservationService.annulerReservation(id).subscribe({
         next: () => {
           alert("✅ Billet annulé et client remboursé (Mail envoyé).");
           this.chargerDonnees();
         },
         error: () => alert("❌ Erreur lors de l'annulation.")
       });
    }
  }

  preparerEchange(res: any) {
    this.reservationAEchanger = res;
    // On charge le catalogue des voyages disponibles
    this.voyageService.getTousLesVoyages().subscribe((vData: any) => {
      const voyagesBruts = vData?.results || vData?.content || vData?._embedded?.voyages || vData;
      this.voyagesDisponibles = Array.isArray(voyagesBruts) ? voyagesBruts : [];
      this.cdr.detectChanges();
      // On scroll vers la section d'échange
      setTimeout(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }), 100);
    });
  }

  annulerEchange() {
    this.reservationAEchanger = null;
    this.filtrePlaces = null; // On réinitialise le filtre
  }

  // 👉 NOUVEAU : Récupère le nombre de places exact du dossier client
  getNbPlacesAEchanger(): number {
    if (!this.reservationAEchanger) return 1;
    return this.reservationAEchanger.billets?.length || 1;
  }

  validerEchange(nouveauVoyageId: number) {
    if (confirm("🔄 Confirmer l'échange vers ce nouveau vol ?")) {
      const baseUrl = this.authService.getBaseUrl();
      const isDjango = this.serveurService.getBackend() === 'django';
      const url = `${baseUrl}/reservations/${this.reservationAEchanger.id}/echanger${isDjango ? '/' : ''}`;

      const payload = { nouveauVoyageId: Number(nouveauVoyageId) };

      this.http.post(url, payload).subscribe({
        next: () => {
          alert("✅ Échange réussi ! Un nouveau billet a été généré et envoyé au client.");
          this.reservationAEchanger = null;
          this.filtrePlaces = null;
          this.chargerDonnees();
        },
        error: (err) => {
          const message = err.error?.erreur || err.error?.error || "Erreur serveur";
          alert("❌ Échec de l'échange : " + message);
        }
      });
    }
  }

  get voyagesFiltres() {
    return this.voyagesDisponibles.filter(v => {
      // 1. Uniquement les voyages "A_VENIR"
      const statut = (v.statut || (v as any).statut || 'A_VENIR').toUpperCase();
      if (statut !== 'A_VENIR') return false;

      // 2. Uniquement si le nombre de places est supérieur à 0
      const places = (v.placesRestantes !== undefined) ? v.placesRestantes : (v as any).places_restantes;
      if (places <= 0) return false;
      
      // 👉 3. NOUVEAU : Le filtre dynamique renseigné par l'admin
      if (this.filtrePlaces !== null && places < this.filtrePlaces) return false;

      const depart = (v.villeDepart || (v as any).ville_depart || '').toLowerCase();
      const arrivee = (v.villeArrivee || (v as any).ville_arrivee || '').toLowerCase();
      const globale = this.texteRecherche.toLowerCase();

      const matchGlobal = !this.texteRecherche || depart.includes(globale) || arrivee.includes(globale) || v.id.toString() === globale;
      const matchDepart = !this.filtreDepart || depart.includes(this.filtreDepart.toLowerCase());
      const matchArrivee = !this.filtreArrivee || arrivee.includes(this.filtreArrivee.toLowerCase());
      
      let matchDate = true;
      if (this.filtreDate && v.segments && v.segments.length > 0) {
        const heureDep = v.segments[0].heureDepart || v.segments[0].heure_depart || '';
        matchDate = heureDep.startsWith(this.filtreDate);
      }

      return matchGlobal && matchDepart && matchArrivee && matchDate;
    });
  }

  retour() {
    this.router.navigate(['/admin/utilisateurs']);
  }
}
<div class="crud-section">
  <div class="section-header" style="justify-content: flex-start; gap: 20px;">
    <button class="btn-action" style="padding: 10px; border-radius: 5px; font-weight: bold;" (click)="retour()">⬅ Retour</button>
    <h3>Billetterie Client - Utilisateur #{{ utilisateurId }}</h3>
  </div>

  @if (isLoading) {
    <p>Chargement des billets...</p>
  } @else {
    <table class="admin-table">
      <thead>
        <tr>
          <th>N° Résa</th>
          <th>Trajet actuel</th>
          <th>Date Résa</th>
          <th>Statut</th>
          <th>Actions Administrateur</th>
        </tr>
      </thead>
      <tbody>
        @for (r of reservations; track r.id) {
          <tr [style.opacity]="r.statut === 'ANNULE' ? '0.6' : '1'">
            <td><strong>#{{ r.id }}</strong></td>
            <td>{{ r.voyage?.villeDepart || r.voyage?.ville_depart }} ➔ {{ r.voyage?.villeArrivee || r.voyage?.ville_arrivee }}</td>
            <td>{{ (r.dateReservation || r.date_confirmation || r.date_reservation) | date:'short' }}</td>
            <td>
              <span class="badge-statut" [ngClass]="r.statut">{{ r.statut }}</span>
            </td>
            <td class="action-cells">
              @if (r.statut === 'ANNULE' || r.statut === 'REMBOURSE') {
                <span style="color: #ef4444; font-weight: bold; background: #fee2e2; padding: 6px 10px; border-radius: 6px; display: inline-block;">
                  🚫 Client déjà remboursé
                </span>
              } @else if (r.statut === 'CONFIRME') {
                <button class="btn-action btn-edit" (click)="preparerEchange(r)">🔄 Échanger</button>
                <button class="btn-action btn-delete" (click)="annulerReservation(r.id)">💸 Annuler & Rembourser</button>
              } @else {
                <span style="color: #64748b; font-style: italic;">En attente de paiement</span>
              }
            </td>
          </tr>
        }
      </tbody>
    </table>
  }

  @if (reservationAEchanger) {
    <div style="margin-top: 50px; padding: 30px; background: #f8fafc; border: 2px dashed #3b82f6; border-radius: 12px;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
        <h3 style="color: #1e293b; margin: 0;">🔄 Reloger le billet #{{ reservationAEchanger.id }}</h3>
        <button class="btn-action" style="color: #ef4444;" (click)="annulerEchange()">✖ Annuler l'échange</button>
      </div>

      <div style="background-color: #fef08a; color: #854d0e; padding: 12px 15px; border-radius: 8px; margin-bottom: 20px; font-weight: bold; border: 1px solid #fde047; display: flex; align-items: center; gap: 10px;">
        <span style="font-size: 1.2rem;">💡</span>
        <span>Le dossier de ce client contient <strong>{{ getNbPlacesAEchanger() }} place(s)</strong>. Il est conseillé de filtrer les vols ayant au moins cette capacité.</span>
      </div>

      <div class="filter-row">
        <div class="filter-group">
          <label>Départ</label>
          <input type="text" [(ngModel)]="filtreDepart" placeholder="Ex: Paris...">
        </div>
        <div class="filter-group">
          <label>Arrivée</label>
          <input type="text" [(ngModel)]="filtreArrivee" placeholder="Ex: Lyon...">
        </div>
        <div class="filter-group">
          <label>Date</label>
          <input type="date" [(ngModel)]="filtreDate">
        </div>
        <div class="filter-group">
          <label>Places Min.</label>
          <input type="number" [(ngModel)]="filtrePlaces" placeholder="Ex: {{ getNbPlacesAEchanger() }}">
        </div>
      </div>

      <table class="admin-table">
        <thead>
          <tr>
            <th>ID Vol</th>
            <th>Itinéraire</th>
            <th>Places restantes</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @for (v of voyagesFiltres; track v.id) {
            <tr>
              <td>#{{ v.id }}</td>
              <td>{{ v.villeDepart || v.ville_depart }} ➔ {{ v.villeArrivee || v.ville_arrivee }}</td>
              <td><strong>{{ v.placesRestantes || v.places_restantes }}</strong></td>
              <td>
                @if ((v.placesRestantes || v.places_restantes) < getNbPlacesAEchanger()) {
                  <div style="display: flex; flex-direction: column; gap: 5px;">
                    <span style="color: #ef4444; font-size: 0.85rem; font-weight: bold;">❌ Pas assez de places</span>
                    <button class="btn-action" style="background: #e2e8f0; color: #94a3b8; border: none; cursor: not-allowed;" disabled>
                      Transfert impossible
                    </button>
                  </div>
                } @else {
                  <button class="btn-action" style="background: #10b981; color: white; border: none;" (click)="validerEchange(v.id)">
                    ✅ Transférer sur ce vol
                  </button>
                }
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
</div>

// react/agence-de-voyage-react/src/components/admin-utilisateur-reservations/AdminUtilisateurReservations.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ReservationService } from '../../services/reservation.service';
import { VoyageService } from '../../services/voyage.service';
import { ServeurService } from '../../services/serveur.service';
import { AuthService } from '../../services/auth.service';
import '../admin-voyages/AdminVoyages.css';

export const AdminUtilisateurReservationsComponent = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [reservations, setReservations] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const [reservationAEchanger, setReservationAEchanger] = useState<any>(null);
  const [voyagesDisponibles, setVoyagesDisponibles] = useState<any[]>([]);
  
  const [texteRecherche, setTexteRecherche] = useState('');
  const [filtreDepart, setFiltreDepart] = useState('');
  const [filtreArrivee, setFiltreArrivee] = useState('');
  const [filtreDate, setFiltreDate] = useState('');
  const [filtrePlaces, setFiltrePlaces] = useState<number | null>(null);

  useEffect(() => {
    chargerReservations();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const chargerReservations = () => {
    setIsLoading(true);
    ReservationService.getHistoriqueUtilisateur(Number(id)).then((data: any) => {
      const resas = Array.isArray(data?.results || data?.content || data) ? (data?.results || data?.content || data) : [];
      setReservations(resas);
      setIsLoading(false);
    }).catch(() => { setReservations([]); setIsLoading(false); });
  };

  const annulerReservation = (idResa: number) => {
    if (window.confirm("Êtes-vous sûr de vouloir annuler cette réservation ? Le client sera remboursé.")) {
      ReservationService.annulerReservation(idResa)
        .then(() => {
          alert("✅ Réservation annulée.");
          chargerReservations();
        })
        .catch(() => alert("Erreur lors de l'annulation."));
    }
  };

  const preparerEchange = (reservation: any) => {
    setReservationAEchanger(reservation);
    VoyageService.getTousLesVoyages().then((data: any) => {
      const voyagesBruts = Array.isArray(data?.results || data?.content || data) ? (data?.results || data?.content || data) : [];
      setVoyagesDisponibles(voyagesBruts);
    });
  };

  const annulerEchange = () => {
    setReservationAEchanger(null);
    setFiltrePlaces(null);
  };

  const getNbPlacesAEchanger = (): number => {
    if (!reservationAEchanger) return 0;
    return reservationAEchanger.billets ? reservationAEchanger.billets.length : (reservationAEchanger.nbPlacesDemandees || 1);
  };

  // 👉 CORRECTION : Méthode POST stricte, exactement comme dans Angular !
  const validerEchange = async (nouveauVoyageId: number) => {
    if (!reservationAEchanger) return;
    if (window.confirm("Confirmer le transfert de ce client vers ce nouveau vol ?")) {
      const baseUrl = AuthService.getBaseUrl();
      const isDjango = ServeurService.getBackend() === 'django';
      const url = `${baseUrl}/reservations/${reservationAEchanger.id}/echanger${isDjango ? '/' : ''}`;
      
      const payload = { nouveauVoyageId: Number(nouveauVoyageId) };

      try {
        const token = AuthService.getToken();
        const response = await fetch(url, {
          method: 'POST', // <-- Le POST qui manquait !
          headers: {
            'Content-Type': 'application/json',
            ...(token ? { 'Authorization': `Bearer ${token}` } : {})
          },
          body: JSON.stringify(payload)
        });

        if (!response.ok) {
          const err = await response.json().catch(() => ({}));
          throw err;
        }

        alert("✅ Échange effectué avec succès ! Un nouveau billet a été généré.");
        setReservationAEchanger(null);
        setFiltrePlaces(null);
        chargerReservations();
      } catch (err: any) {
        const message = err?.erreur || err?.error || "Erreur serveur";
        alert("❌ Échec de l'échange : " + message);
      }
    }
  };

  const getVoyagesFiltres = () => {
    return voyagesDisponibles.filter(v => {
      const statut = (v.statut || v.statut || 'A_VENIR').toUpperCase();
      if (statut !== 'A_VENIR') return false;
      const places = (v.placesRestantes !== undefined) ? v.placesRestantes : v.places_restantes;
      if (places <= 0 || (filtrePlaces !== null && places < filtrePlaces)) return false;

      const depart = (v.villeDepart || v.ville_depart || '').toLowerCase();
      const arrivee = (v.villeArrivee || v.ville_arrivee || '').toLowerCase();
      const globale = texteRecherche.toLowerCase();

      const matchGlobal = !texteRecherche || depart.includes(globale) || arrivee.includes(globale) || v.id.toString() === globale;
      const matchDepart = !filtreDepart || depart.includes(filtreDepart.toLowerCase());
      const matchArrivee = !filtreArrivee || arrivee.includes(filtreArrivee.toLowerCase());
      
      let matchDate = true;
      if (filtreDate && v.segments && v.segments.length > 0) {
        matchDate = (v.segments[0].heureDepart || v.segments[0].heure_depart || '').startsWith(filtreDate);
      }
      return matchGlobal && matchDepart && matchArrivee && matchDate;
    });
  };

  const retour = () => {
    if (reservationAEchanger) annulerEchange();
    else navigate(-1);
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="crud-section">
      <div className="section-header" style={{ justifyContent: 'flex-start', gap: '20px' }}>
        <button className="btn-action" style={{ padding: '10px', borderRadius: '5px', fontWeight: 'bold' }} onClick={retour}>⬅ Retour</button>
        <h3>Billetterie Client - Utilisateur #{id}</h3>
      </div>

      {isLoading ? <p>Chargement des billets...</p> : !reservationAEchanger ? (
        <table className="admin-table">
          <thead>
            <tr>
              <th>N° Résa</th>
              <th>Trajet actuel</th>
              <th>Date Résa</th>
              <th>Places</th>
              <th>Statut</th>
              <th>Actions Administrateur</th>
            </tr>
          </thead>
          <tbody>
            {reservations.map(r => (
              <tr key={r.id} style={{ opacity: r.statut === 'ANNULE' ? '0.6' : '1' }}>
                <td><strong>#{r.id}</strong></td>
                <td>{r.voyage?.villeDepart || r.voyage?.ville_depart} ➔ {r.voyage?.villeArrivee || r.voyage?.ville_arrivee}</td>
                <td>{formatDate(r.dateReservation || r.date_confirmation || r.date_reservation)}</td>
                <td>
                  <span style={{ background: '#f1f5f9', padding: '4px 10px', borderRadius: '20px', fontWeight: 'bold' }}>
                    {r.billets ? r.billets.length : (r.nbPlacesDemandees || 1)}
                  </span>
                </td>
                <td><span className={`badge-statut ${r.statut}`}>{r.statut}</span></td>
                <td className="action-cells">
                  {r.statut === 'ANNULE' || r.statut === 'REMBOURSE' ? (
                    <span style={{ color: '#ef4444', fontWeight: 'bold', background: '#fee2e2', padding: '6px 10px', borderRadius: '6px', display: 'inline-block' }}>
                      🚫 Client déjà remboursé
                    </span>
                  ) : r.statut === 'CONFIRME' ? (
                    <div style={{ display: 'flex', gap: '8px' }}>
                      <button className="btn-action btn-view" onClick={() => preparerEchange(r)}>🔄 Échanger</button>
                      <button className="btn-action btn-delete" onClick={() => annulerReservation(r.id)}>💸 Annuler & Rembourser</button>
                    </div>
                  ) : (
                    <span style={{ color: '#64748b', fontStyle: 'italic' }}>En attente de paiement</span>
                  )}
                </td>
              </tr>
            ))}
            {reservations.length === 0 && (
              <tr><td colSpan={6} style={{ textAlign: 'center', padding: '25px', color: '#64748b' }}>Aucune réservation pour ce client.</td></tr>
            )}
          </tbody>
        </table>
      ) : (
        <div style={{ marginTop: '50px', padding: '30px', background: '#f8fafc', border: '2px dashed #3b82f6', borderRadius: '12px' }}>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
            <h3 style={{ color: '#1e293b', margin: 0 }}>
              🔄 Reloger le billet #{reservationAEchanger.id}
            </h3>
            <button className="btn-action" style={{ color: '#ef4444' }} onClick={annulerEchange}>✖ Annuler l'échange</button>
          </div>

          <div style={{ backgroundColor: '#fef08a', color: '#854d0e', padding: '12px 15px', borderRadius: '8px', marginBottom: '20px', fontWeight: 'bold', border: '1px solid #fde047', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ fontSize: '1.2rem' }}>💡</span>
            <span>Le dossier de ce client contient <strong>{getNbPlacesAEchanger()} place(s)</strong>. Il est conseillé de filtrer les vols ayant au moins cette capacité.</span>
          </div>
          
          <div className="filter-row">
            <div className="filter-group"><label>Départ</label><input type="text" value={filtreDepart} onChange={e => setFiltreDepart(e.target.value)} /></div>
            <div className="filter-group"><label>Arrivée</label><input type="text" value={filtreArrivee} onChange={e => setFiltreArrivee(e.target.value)} /></div>
            <div className="filter-group"><label>Date précise</label><input type="date" value={filtreDate} onChange={e => setFiltreDate(e.target.value)} /></div>
            <div className="filter-group"><label>Places Minimum</label><input type="number" value={filtrePlaces || ''} onChange={e => setFiltrePlaces(e.target.value === '' ? null : Number(e.target.value))} placeholder={`Ex: ${getNbPlacesAEchanger()}`} /></div>
          </div>

          <table className="admin-table">
            <thead><tr><th>ID Vol</th><th>Itinéraire</th><th>Places restantes</th><th>Action</th></tr></thead>
            <tbody>
              {getVoyagesFiltres().map(v => (
                <tr key={v.id}>
                  <td>#{v.id}</td>
                  <td>{v.villeDepart || v.ville_depart} ➔ {v.villeArrivee || v.ville_arrivee}</td>
                  <td><strong>{v.placesRestantes !== undefined ? v.placesRestantes : v.places_restantes}</strong></td>
                  <td>
                    {(v.placesRestantes !== undefined ? v.placesRestantes : v.places_restantes) < getNbPlacesAEchanger() ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
                        <span style={{ color: '#ef4444', fontSize: '0.85rem', fontWeight: 'bold' }}>❌ Pas assez de places</span>
                        <button className="btn-action" style={{ background: '#e2e8f0', color: '#94a3b8', border: 'none', cursor: 'not-allowed' }} disabled>Transfert impossible</button>
                      </div>
                    ) : (
                      <button className="btn-action" style={{ background: '#10b981', color: 'white', border: 'none' }} onClick={() => validerEchange(v.id)}>✅ Transférer sur ce vol</button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
