// angular/agence-voyage/src/app/components/paiement/paiement.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { loadStripe, Stripe, StripeElements } from '@stripe/stripe-js'; 

import { ServeurService } from '../../services/serveur.service';
import { ReservationService } from '../../services/reservation.service';
import { environment } from '../../../environments/environment.development';

@Component({
  selector: 'app-paiement',
  standalone: true,
  imports: [CommonModule], 
  templateUrl: './paiement.component.html',
  styleUrls: ['./paiement.component.css']
})
export class PaiementComponent implements OnInit {
  reservationId!: number;
  prixTotal!: number;

  private http = inject(HttpClient);
  private serveurService = inject(ServeurService);
  private reservationService = inject(ReservationService);
  private cdr = inject(ChangeDetectorRef);
  private route = inject(ActivatedRoute);
  private router = inject(Router);

  isLoading = false;
  message = '';
  ticketRecu = false;

  private stripe: Stripe | null = null;
  private elements: StripeElements | null = null;

  async ngOnInit() {
    this.reservationId = Number(this.route.snapshot.paramMap.get('reservationId'));
    this.prixTotal = Number(this.route.snapshot.paramMap.get('prix'));
    
    this.stripe = await loadStripe('pk_test_51TSDQQ233VR20pvSSLzE8e6TDSvgE8UyawtC93zOX8P0rajCT4cfmgdgNUQzrNMw3IzhMTUrbJzdqXR5SxULS1iF00DNWsnDdi');
    this.demanderTicketPaiement();
  }

  private demanderTicketPaiement() {
    const backend = this.serveurService.getBackend();
    const url = backend === 'spring' 
      ? `${environment.urls[backend]}/paiement/create-intent`
      : `${environment.urls[backend]}/paiement/create-intent/`;

    this.http.post<{clientSecret: string}>(url, { prixTotal: this.prixTotal }).subscribe({
      next: (res) => {
        if (res && res.clientSecret && this.stripe) {
          
          this.elements = this.stripe.elements({
            clientSecret: res.clientSecret,
            locale: 'fr',
            appearance: { theme: 'stripe' }
          });

          const paymentElement = this.elements.create('payment', { layout: 'tabs' });
          
          this.ticketRecu = true;
          this.cdr.detectChanges(); 

          setTimeout(() => {
            paymentElement.mount('#payment-element-div');
          }, 0);

        } else {
          this.message = "Erreur : Ticket secret non reçu.";
          this.cdr.detectChanges();
        }
      },
      error: (err) => {
        this.message = "Échec de la communication avec l'API de paiement.";
        this.cdr.detectChanges();
      }
    });
  }

  async payer() {
    if (this.isLoading || !this.stripe || !this.elements) return;
    
    this.isLoading = true;
    this.message = "Traitement du paiement en cours...";
    this.cdr.detectChanges();

    const { error, paymentIntent } = await this.stripe.confirmPayment({
      elements: this.elements,
      redirect: 'if_required' 
    });

    if (error) {
      this.isLoading = false;
      this.message = "❌ Paiement refusé : " + error.message;
      this.cdr.detectChanges();
    } else if (paymentIntent && paymentIntent.status === 'succeeded') {
      
      this.message = "✅ Paiement Stripe validé ! Mise à jour de votre billet...";
      this.cdr.detectChanges();

      // 👉 LA MAGIE EST ICI : On envoie le "paymentIntent.id" (le reçu Stripe) au backend !
      this.reservationService.confirmerPaiement(this.reservationId, paymentIntent.id).subscribe({
        next: () => {
          this.isLoading = false;
          this.message = "✅ Billet confirmé ! Bon voyage !";
          this.cdr.detectChanges();
          setTimeout(() => this.router.navigate(['/historique']), 2000);
        },
        error: (err) => {
          this.isLoading = false;
          this.message = "⚠️ Paiement accepté, mais erreur de confirmation côté serveur.";
          this.cdr.detectChanges();
        }
      });
      
    } else {
      this.isLoading = false;
      this.message = "Erreur inattendue.";
      this.cdr.detectChanges();
    }
  }
}
<div class="paiement-container">
  
  <div class="header">
    <h2>Paiement Sécurisé</h2>
    <p>Validation de la réservation N°{{ reservationId }}</p>
  </div>

  <div class="montant-box">
    <span>Montant à régler :</span>
    <strong>{{ prixTotal }} €</strong>
  </div>

  @if (ticketRecu) {
    <div class="stripe-zone">
      
      <!-- 👉 C'EST ICI QUE STRIPE VA INJECTER LE FORMULAIRE -->
      <div id="payment-element-div"></div>

      <button class="btn-payer" (click)="payer()" [disabled]="isLoading">
        @if (isLoading) {
          <span class="spinner">⏳</span> Traitement...
        } @else {
          🔒 Payer {{ prixTotal }} €
        }
      </button>

      @if (message) {
        <div class="message-alerte" 
             [class.success]="message.includes('✅')" 
             [class.error]="message.includes('❌') || message.includes('Erreur') || message.includes('Échec')">
          {{ message }}
        </div>
      }
    </div>
  } @else if (!message) {
    <div class="loading-zone">
      <span class="spinner">⏳</span> Connexion à la banque...
    </div>
  } @else {
    <div class="message-alerte error">{{ message }}</div>
  }

</div>

// react/agence-de-voyage-react/src/components/paiement/Paiement.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ServeurService } from '../../services/serveur.service';
import { ReservationService } from '../../services/reservation.service';
import { environment } from '../../environments/environment.development';
import { apiFetch } from '../../interceptors/jwt.interceptor';
import './Paiement.css';
import { type Stripe, type StripeElements, loadStripe } from '@stripe/stripe-js';

// 👉 CORRECTION 1 : On charge Stripe UNE SEULE FOIS en dehors du composant
const stripePromise = loadStripe('pk_test_51TSDQQ233VR20pvSSLzE8e6TDSvgE8UyawtC93zOX8P0rajCT4cfmgdgNUQzrNMw3IzhMTUrbJzdqXR5SxULS1iF00DNWsnDdi');

export const PaiementComponent = () => {
  const { reservationId, prix } = useParams<{ reservationId: string, prix: string }>();
  const navigate = useNavigate();

  const [isLoading, setIsLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [ticketRecu, setTicketRecu] = useState(false);
  
  const [stripeObj, setStripeObj] = useState<Stripe | null>(null);
  const [elementsObj, setElementsObj] = useState<StripeElements | null>(null);

  useEffect(() => {
    const initStripe = async () => {
      // 👉 On attend la promesse globale
      const stripeInstance = await stripePromise;
      setStripeObj(stripeInstance);

      const backend = ServeurService.getBackend();
      const url = backend === 'spring' 
        ? `${environment.urls[backend]}/paiement/create-intent`
        : `${environment.urls[backend]}/paiement/create-intent/`;

      apiFetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prixTotal: Number(prix) })
      })
        .then(res => res.json())
        .then(res => {
          if (res && res.clientSecret && stripeInstance) {
            const elems = stripeInstance.elements({
              clientSecret: res.clientSecret,
              locale: 'fr',
              appearance: { theme: 'stripe' }
            });
            setElementsObj(elems);
            
            const paymentElement = elems.create('payment', { layout: 'tabs' });
            setTicketRecu(true);
            
            setTimeout(() => {
              paymentElement.mount('#payment-element-div');
            }, 0);
          } else {
            setMessage("Erreur : Ticket secret non reçu.");
          }
        })
        .catch(() => {
          setMessage("Échec de la communication avec l'API de paiement.");
        });
    };

    initStripe();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prix]);

  const payer = async () => {
    if (isLoading || !stripeObj || !elementsObj) return;
    
    setIsLoading(true);
    setMessage("Traitement du paiement en cours...");

    try {
      // 👉 CORRECTION 2 : On sécurise le paiement avec un try/catch
      const { error, paymentIntent } = await stripeObj.confirmPayment({
        elements: elementsObj,
        redirect: 'if_required' 
      });

      if (error) {
        setIsLoading(false);
        setMessage("❌ Paiement refusé : " + error.message);
      } else if (paymentIntent && paymentIntent.status === 'succeeded') {
        setMessage("✅ Paiement Stripe validé ! Mise à jour de votre billet...");

        ReservationService.confirmerPaiement(Number(reservationId), paymentIntent.id)
          .then(() => {
            setIsLoading(false);
            setMessage("✅ Billet confirmé ! Bon voyage !");
            setTimeout(() => navigate('/historique'), 2000);
          })
          .catch(() => {
            setIsLoading(false);
            setMessage("⚠️ Paiement accepté, mais erreur de confirmation côté serveur.");
          });
      } else {
        setIsLoading(false);
        setMessage("Erreur inattendue.");
      }
    } catch (err: any) {
      setIsLoading(false);
      setMessage("❌ Erreur d'intégration Stripe : " + err.message);
    }
  };

  return (
    <div className="paiement-container">
      <div className="header">
        <h2>Paiement Sécurisé</h2>
        <p>Validation de la réservation N°{reservationId}</p>
      </div>

      <div className="montant-box">
        <span>Montant à régler :</span>
        <strong>{prix} €</strong>
      </div>

      {ticketRecu ? (
        <div className="stripe-zone">
          <div id="payment-element-div"></div>

          <button className="btn-payer" onClick={payer} disabled={isLoading}>
            {isLoading ? (
              <><span className="spinner">⏳</span> Traitement...</>
            ) : (
              `🔒 Payer ${prix} €`
            )}
          </button>

          {message && (
            <div className={`message-alerte ${message.includes('✅') ? 'success' : message.includes('❌') || message.includes('Erreur') || message.includes('Échec') ? 'error' : ''}`}>
              {message}
            </div>
          )}
        </div>
      ) : !message ? (
        <div className="loading-zone">
          <span className="spinner">⏳</span> Connexion à la banque...
        </div>
      ) : (
        <div className="message-alerte error">{message}</div>
      )}
    </div>
  );
};
