// angular/agence-voyage/src/app/components/admin-utilisateur-avis/admin-utilisateur-avis.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { AvisService } from '../../services/avis.service';

@Component({
  selector: 'app-admin-utilisateur-avis',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './admin-utilisateur-avis.component.html',
  styleUrls: ['../admin-voyages/admin-voyages.component.css']
})
export class AdminUtilisateurAvisComponent implements OnInit {
  private avisService = inject(AvisService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private cdr = inject(ChangeDetectorRef);

  utilisateurId!: number;
  avisList: any[] = [];
  isLoading = true;

  ngOnInit() {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.utilisateurId = Number(idParam);
      this.chargerAvisUtilisateur();
    }
  }

  chargerAvisUtilisateur() {
    this.isLoading = true;
    this.cdr.detectChanges();

    // 👉 Retour à la source : L'API nous donne enfin les bons auteurs !
    this.avisService.getTous().subscribe({
      next: (data: any) => {
        try {
          const donneesBrutes = data?.results || data?.content || data?._embedded?.avis || data;
          const tousLesAvis = Array.isArray(donneesBrutes) ? donneesBrutes : [];

          this.avisList = tousLesAvis.filter((a: any) => {
            const authorId = this.getAuteurId(a);
            return Number(authorId) === Number(this.utilisateurId);
          });
        } finally {
          this.isLoading = false;
          this.cdr.detectChanges();
        }
      },
      error: () => {
        this.avisList = [];
        this.isLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  getAuteurId(avis: any): number {
    return avis.utilisateur?.id || avis.utilisateur_id || avis.utilisateur;
  }

  supprimerAvis(id: number) {
    if (confirm("Supprimer définitivement cet avis pour non-respect des règles ?")) {
      this.avisService.supprimer(id).subscribe({
        next: () => {
          alert('✅ Avis censuré.');
          this.chargerAvisUtilisateur();
        },
        error: () => alert("❌ Erreur lors de la suppression de l'avis.")
      });
    }
  }

  retour() {
    this.router.navigate(['/admin/utilisateurs']);
  }
}
<div class="crud-section">
  
  <div class="section-header" style="justify-content: flex-start; gap: 20px;">
    <button class="btn-action" style="padding: 10px; border-radius: 5px; font-weight: bold;" (click)="retour()">⬅ Retour</button>
    <h3>Modération des Avis - Utilisateur #{{ utilisateurId }}</h3>
  </div>

  @if (isLoading) {
    <p>Chargement des avis...</p>
  } @else {
    <table class="admin-table">
      <thead>
        <tr>
          <th>ID Avis</th>
          <th>ID Voyage Cible</th>
          <th>Note</th>
          <th>Commentaire laissé</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        @for (a of avisList; track a.id) {
          <tr>
            <td><strong>#{{ a.id }}</strong></td>
            <td>Voyage #{{ a.voyage?.id || a.voyage_id || a.voyage }}</td>
            <td><strong>{{ a.note }} / 5 ⭐</strong></td>
            <td style="max-width: 400px; font-style: italic;">"{{ a.commentaire || 'Avis uniquement sous forme de note' }}"</td>
            <td class="action-cells">
              <button class="btn-action btn-delete" (click)="supprimerAvis(a.id)">🗑️ Censurer</button>
            </td>
          </tr>
        }
        @if (avisList.length === 0) {
          <tr><td colspan="5" style="text-align: center; color: #94a3b8; padding: 25px;">Cet utilisateur n'a laissé aucun avis.</td></tr>
        }
      </tbody>
    </table>
  }
</div>

// react/agence-de-voyage-react/src/components/admin-utilisateur-avis/AdminUtilisateurAvis.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { AvisService } from '../../services/avis.service';
import '../admin-voyages/AdminVoyages.css';

export const AdminUtilisateurAvisComponent = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [avisList, setAvisList] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (id) chargerAvis(Number(id));
  }, [id]);

  const chargerAvis = (uid: number) => {
    setIsLoading(true);
    AvisService.getTous().then((data: any) => {
      const tousLesAvis = Array.isArray(data?.results || data?.content || data?._embedded?.avis || data) 
        ? (data?.results || data?.content || data?._embedded?.avis || data) : [];
      setAvisList(tousLesAvis.filter((a: any) => Number(a.utilisateur?.id || a.utilisateur_id || a.utilisateur) === uid));
      setIsLoading(false);
    }).catch(() => { setAvisList([]); setIsLoading(false); });
  };

  const supprimerAvis = (idAvis: number) => {
    if (window.confirm("Supprimer définitivement cet avis pour non-respect des règles ?")) {
      AvisService.supprimer(idAvis).then(() => {
        // 👉 CORRECTION : Popup ajouté
        alert('✅ Avis censuré.');
        chargerAvis(Number(id));
      }).catch(() => alert('Erreur'));
    }
  };

  return (
    <div className="crud-section">
      <div className="section-header" style={{ justifyContent: 'flex-start', gap: '20px' }}>
        <button className="btn-action" style={{ padding: '10px', borderRadius: '5px', fontWeight: 'bold' }} onClick={() => navigate(-1)}>⬅ Retour</button>
        <h3>Modération des Avis - Utilisateur #{id}</h3>
      </div>
      {isLoading ? <p>Chargement des avis...</p> : (
        <table className="admin-table">
          <thead><tr><th>ID Avis</th><th>ID Voyage</th><th>Note</th><th>Commentaire</th><th>Action</th></tr></thead>
          <tbody>
            {avisList.map(a => (
              <tr key={a.id}>
                <td><strong>#{a.id}</strong></td>
                <td>Voyage #{a.voyage?.id || a.voyage_id || a.voyage}</td>
                <td><strong>{a.note} / 5 ⭐</strong></td>
                <td style={{ maxWidth: '400px', fontStyle: 'italic' }}>"{a.commentaire || 'Avis note seule'}"</td>
                <td className="action-cells"><button className="btn-action btn-delete" onClick={() => supprimerAvis(a.id)}>🗑️ Censurer</button></td>
              </tr>
            ))}
            {avisList.length === 0 && (
              <tr><td colSpan={5} style={{ textAlign: 'center', color: '#94a3b8', padding: '25px' }}>Aucun avis pour cet utilisateur.</td></tr>
            )}
          </tbody>
        </table>
      )}
    </div>
  );
};
