// react/agence-de-voyage-react/src/components/admin-voyage-form/AdminVoyageForm.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { VoyageService } from '../../services/voyage.service';
import { ServeurService } from '../../services/serveur.service';
import './AdminVoyageForm.css';

export const AdminVoyageFormComponent = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [voyageId, setVoyageId] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [erreurFormulaire, setErreurFormulaire] = useState('');

  const [formVoyage, setFormVoyage] = useState({
    villeDepart: '',
    villeArrivee: '',
    prixTotal: 0,
    nombrePlacesTotal: 0,
    statut: 'A_VENIR',
    segments: [] as any[]
  });

  useEffect(() => {
    if (id) {
      setVoyageId(Number(id));
      chargerVoyage(Number(id));
    } else {
      setVoyageId(null);
      setIsLoading(false);
      verifierFormulaire({
        villeDepart: '', villeArrivee: '', prixTotal: 0, nombrePlacesTotal: 0, statut: 'A_VENIR', segments: []
      });
    }
  }, [id]);

  const chargerVoyage = (vId: number) => {
    VoyageService.getTousLesVoyages()
      .then((data: any) => {
        const donneesBrutes = data?.results || data?.content || data?._embedded?.voyages || data;
        const liste = Array.isArray(donneesBrutes) ? donneesBrutes : [];
        const trouve = liste.find((v: any) => v.id === vId);

        if (trouve) {
          // On normalise les données pour le formulaire interne React
          const segmentsNormalises = (trouve.segments ? [...trouve.segments] : []).map((s: any) => ({
            villeDepart: s.villeDepart || s.ville_depart || '',
            villeArrivee: s.villeArrivee || s.ville_arrivee || '',
            heureDepart: s.heureDepart || s.heure_depart || '',
            heureArrivee: s.heureArrivee || s.heure_arrivee || ''
          }));

          setFormVoyage({
            villeDepart: trouve.villeDepart || trouve.ville_depart || '',
            villeArrivee: trouve.villeArrivee || trouve.ville_arrivee || '',
            prixTotal: trouve.prixTotal || trouve.prix_total || 0,
            nombrePlacesTotal: trouve.nombrePlacesTotal || trouve.nombre_places_total || 0,
            statut: trouve.statut || 'A_VENIR',
            segments: segmentsNormalises
          });
          setIsLoading(false);
        } else {
          alert("Voyage introuvable.");
          navigate('/admin/voyages');
        }
      })
      .catch(() => {
        alert("Erreur serveur.");
        navigate('/admin/voyages');
      });
  };

  // --- GESTION DES CHANGEMENTS DE CHAMPS ---
  const handleFieldChange = (field: string, value: any) => {
    const updated = { ...formVoyage, [field]: value };
    setFormVoyage(updated);
    verifierFormulaire(updated);
  };

  const handleSegmentChange = (index: number, field: string, value: string) => {
    const newSegments = [...formVoyage.segments];
    newSegments[index] = { ...newSegments[index], [field]: value };
    const updated = { ...formVoyage, segments: newSegments };
    setFormVoyage(updated);
    verifierFormulaire(updated);
  };

  const ajouterSegment = () => {
    const newSegments = [...formVoyage.segments, { villeDepart: '', villeArrivee: '', heureDepart: '', heureArrivee: '' }];
    const updated = { ...formVoyage, segments: newSegments };
    setFormVoyage(updated);
    verifierFormulaire(updated);
  };

  const supprimerSegment = (index: number) => {
    const newSegments = formVoyage.segments.filter((_, i) => i !== index);
    const updated = { ...formVoyage, segments: newSegments };
    setFormVoyage(updated);
    verifierFormulaire(updated);
  };

  // --- LOGIQUE MÉTIER DE VALIDATION ---
  const verifierFormulaire = (state: typeof formVoyage) => {
    let err = '';

    if (!state.villeDepart || !state.villeArrivee) {
      err = "Les villes de départ et d'arrivée globales sont obligatoires.";
    } else if (state.prixTotal <= 0) {
      err = "Le prix total doit être supérieur à 0.";
    } else if (state.nombrePlacesTotal <= 0) {
      err = "Le nombre de places doit être supérieur à 0.";
    } else if (state.segments.length === 0) {
      err = "Vous devez ajouter au moins un segment de vol.";
    } else {
      for (let i = 0; i < state.segments.length; i++) {
        const s = state.segments[i];
        if (!s.villeDepart || !s.villeArrivee || !s.heureDepart || !s.heureArrivee) {
          err = `Le segment ${i + 1} est incomplet.`;
          break;
        }
        if (new Date(s.heureArrivee) <= new Date(s.heureDepart)) {
          err = `Segment ${i + 1} : L'arrivée doit être après le départ.`;
          break;
        }
        if (i > 0) {
          const prev = state.segments[i - 1];
          if (new Date(s.heureDepart) < new Date(prev.heureArrivee)) {
            err = `Erreur chronologique : Le segment ${i + 1} part avant l'arrivée du segment ${i}.`;
            break;
          }
        }
      }
    }
    setErreurFormulaire(err);
  };

  const sauvegarder = () => {
    if (erreurFormulaire) return;
    const backend = ServeurService.getBackend();
    
    // On convertit les clés selon le backend actif (CamelCase vs SnakeCase)
    const segmentsFormates = formVoyage.segments.map((s: any, index: number) => {
      return backend === 'spring' ? {
        ordre: index + 1, villeDepart: s.villeDepart, villeArrivee: s.villeArrivee, heureDepart: s.heureDepart, heureArrivee: s.heureArrivee
      } : {
        ordre: index + 1, ville_depart: s.villeDepart, ville_arrivee: s.villeArrivee, heure_depart: s.heureDepart, heure_arrivee: s.heureArrivee
      };
    });

    const payload = backend === 'spring' ? {
      villeDepart: formVoyage.villeDepart, villeArrivee: formVoyage.villeArrivee,
      prixTotal: Number(formVoyage.prixTotal), nombrePlacesTotal: Number(formVoyage.nombrePlacesTotal),
      statut: formVoyage.statut, segments: segmentsFormates
    } : {
      ville_depart: formVoyage.villeDepart, ville_arrivee: formVoyage.villeArrivee,
      prix_total: Number(formVoyage.prixTotal), nombre_places_total: Number(formVoyage.nombrePlacesTotal),
      statut: formVoyage.statut, segments: segmentsFormates
    };

    const requete = voyageId 
      ? VoyageService.modifierVoyage(voyageId, payload) 
      : VoyageService.creerVoyage(payload);

    requete
      .then(() => {
        alert("✅ Voyage enregistré avec succès !");
        navigate('/admin/voyages');
      })
      .catch(() => alert("❌ Erreur lors de l'enregistrement."));
  };

  const annuler = () => navigate('/admin/voyages');

  return (
    <div className="form-page-container">
      <div className="header-action">
        <h2>{voyageId ? 'Modifier le Voyage' : 'Nouveau Voyage'}</h2>
        <button className="btn-back" onClick={annuler}><span>⬅</span> Retour à la liste</button>
      </div>

      {isLoading ? (
        <div style={{ textAlign: 'center', padding: '50px' }}>
          <p>⏳ Chargement des données techniques...</p>
        </div>
      ) : (
        <div className="card-form">
          <div className="form-row">
            <div className="form-group">
              <label>Ville de Départ</label>
              <input type="text" value={formVoyage.villeDepart} onChange={e => handleFieldChange('villeDepart', e.target.value)} placeholder="Ex: Paris" />
            </div>
            <div className="form-group">
              <label>Ville d'Arrivée</label>
              <input type="text" value={formVoyage.villeArrivee} onChange={e => handleFieldChange('villeArrivee', e.target.value)} placeholder="Ex: New York" />
            </div>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label>Prix Total (€)</label>
              <input type="number" value={formVoyage.prixTotal} onChange={e => handleFieldChange('prixTotal', e.target.value)} placeholder="0.00" />
            </div>
            <div className="form-group">
              <label>Nombre de Places</label>
              <input type="number" value={formVoyage.nombrePlacesTotal} onChange={e => handleFieldChange('nombrePlacesTotal', e.target.value)} placeholder="Capacité de l'avion" />
            </div>
          </div>

          <div className="form-group" style={{ marginBottom: '35px' }}>
            <label>Statut du Voyage</label>
            <select value={formVoyage.statut} onChange={e => handleFieldChange('statut', e.target.value)} style={{ padding: '10px', borderRadius: '6px', border: '1px solid #cbd5e1', width: '100%', maxWidth: '300px' }}>
              <option value="A_VENIR">À Venir (Réservations ouvertes)</option>
              <option value="EN_COURS">En Cours (Vol en cours)</option>
              <option value="TERMINE">Terminé (Vol fini)</option>
              <option value="ANNULE">Annulé (Verrouillé)</option>
            </select>
          </div>

          <div className="segments-section">
            <div className="segments-header">
              <h3>Itinéraire & Vols (Segments)</h3>
              <button className="btn-add-segment" onClick={ajouterSegment}>+ Ajouter une escale/vol</button>
            </div>

            <div className="segments-container">
              {formVoyage.segments.length === 0 && (
                <p style={{ color: '#94a3b8', fontStyle: 'italic' }}>Aucun segment défini. Cliquez sur + Ajouter pour commencer.</p>
              )}

              {formVoyage.segments.map((seg, index) => (
                <div className="segment-card" key={index}>
                  <div className="segment-card-header">
                    <span className="segment-number">Vol {index + 1}</span>
                    <button className="btn-delete-segment" onClick={() => supprimerSegment(index)}>🗑️ Supprimer</button>
                  </div>

                  <div className="form-row" style={{ marginBottom: '15px' }}>
                    <div className="form-group">
                      <label>Ville Départ</label>
                      <input type="text" value={seg.villeDepart} onChange={e => handleSegmentChange(index, 'villeDepart', e.target.value)} placeholder="Départ" />
                    </div>
                    <div className="form-group">
                      <label>Date & Heure Départ</label>
                      <input type="datetime-local" value={seg.heureDepart} onChange={e => handleSegmentChange(index, 'heureDepart', e.target.value)} />
                    </div>
                  </div>

                  <div className="form-row" style={{ marginBottom: '0' }}>
                    <div className="form-group">
                      <label>Ville Arrivée</label>
                      <input type="text" value={seg.villeArrivee} onChange={e => handleSegmentChange(index, 'villeArrivee', e.target.value)} placeholder="Arrivée" />
                    </div>
                    <div className="form-group">
                      <label>Date & Heure Arrivée</label>
                      <input type="datetime-local" value={seg.heureArrivee} onChange={e => handleSegmentChange(index, 'heureArrivee', e.target.value)} />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {erreurFormulaire && (
            <div className="alert-box error"><span>⚠️</span> {erreurFormulaire}</div>
          )}

          <div className="form-actions">
            <button className="btn-cancel" onClick={annuler}>Annuler</button>
            <button className="btn-save" disabled={erreurFormulaire !== ''} onClick={sauvegarder}>
              {voyageId ? '💾 Enregistrer les modifications' : '🚀 Créer le voyage'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// angular/agence-voyage/src/app/components/admin-voyage-form/admin-voyage-form.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { VoyageService } from '../../services/voyage.service';
import { ServeurService } from '../../services/serveur.service';

@Component({
  selector: 'app-admin-voyage-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-voyage-form.component.html',
  styleUrls: ['./admin-voyage-form.component.css']
})
export class AdminVoyageFormComponent implements OnInit {
  private voyageService = inject(VoyageService);
  private serveurService = inject(ServeurService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private cdr = inject(ChangeDetectorRef);

  voyageId: number | null = null;
  isLoading = true;
  erreurFormulaire = '';

  formVoyage: any = { 
    villeDepart: '', 
    villeArrivee: '', 
    prixTotal: 0, 
    nombrePlacesTotal: 0,
    statut: 'A_VENIR', 
    segments: [] 
  };

  ngOnInit() {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.voyageId = Number(idParam);
      this.chargerVoyage(this.voyageId);
    } else {
      this.formVoyage.statut = 'A_VENIR';
      this.ajouterSegment(); 
      this.isLoading = false; 
    }
  }

  chargerVoyage(id: number) {
    this.voyageService.getTousLesVoyages().subscribe({
      next: (data: any) => {
        const donneesBrutes = data?.results || data?.content || data?._embedded?.voyages || data;
        const voyages = Array.isArray(donneesBrutes) ? donneesBrutes : [];
        const voyage = voyages.find((v: any) => v.id === id);
        
        if (voyage) {
          this.formVoyage = {
            villeDepart: voyage.villeDepart || voyage.ville_depart || '',
            villeArrivee: voyage.villeArrivee || voyage.ville_arrivee || '',
            prixTotal: voyage.prixTotal || voyage.prix_total || 0,
            nombrePlacesTotal: voyage.nombrePlacesTotal || voyage.nombre_places_total || 0,
            statut: voyage.statut || 'A_VENIR',
            segments: (voyage.segments || []).map((s: any) => {
              const hDep = s.heureDepart || s.heure_depart || '';
              const hArr = s.heureArrivee || s.heure_arrivee || '';

              return {
                villeDepart: s.villeDepart || s.ville_depart || '',
                villeArrivee: s.villeArrivee || s.ville_arrivee || '',
                heureDepart: hDep ? hDep.substring(0, 16) : '',
                heureArrivee: hArr ? hArr.substring(0, 16) : ''
              };
            })
          };
        }
        
        this.isLoading = false;
        this.verifierFormulaire();
        this.cdr.detectChanges(); 
      },
      error: () => { 
        this.isLoading = false; 
        this.cdr.detectChanges(); 
      }
    });
  }

  ajouterSegment() {
    this.formVoyage.segments.push({
      villeDepart: '', villeArrivee: '', heureDepart: '', heureArrivee: ''
    });
    this.verifierFormulaire();
  }

  supprimerSegment(index: number) {
    this.formVoyage.segments.splice(index, 1);
    this.verifierFormulaire();
  }

  verifierFormulaire() {
    this.erreurFormulaire = '';

    if (!this.formVoyage.villeDepart || !this.formVoyage.villeArrivee) {
      this.erreurFormulaire = "Les villes de départ et d'arrivée du voyage sont obligatoires.";
      return;
    }
    if (this.formVoyage.prixTotal <= 0) {
      this.erreurFormulaire = "Le prix total doit être supérieur à 0.";
      return;
    }
    if (this.formVoyage.nombrePlacesTotal <= 0) {
      this.erreurFormulaire = "Le nombre de places doit être supérieur à 0.";
      return;
    }
    if (this.formVoyage.segments.length === 0) {
      this.erreurFormulaire = "Il faut au moins 1 segment pour ce voyage.";
      return;
    }

    // ==========================================
    // 🌍 NOUVELLES RÈGLES DE COHÉRENCE DES VILLES
    // ==========================================
    
    const villeDepGlobale = this.formVoyage.villeDepart.trim().toLowerCase();
    const villeArrGlobale = this.formVoyage.villeArrivee.trim().toLowerCase();
    const premierSegDep = (this.formVoyage.segments[0].villeDepart || '').trim().toLowerCase();
    const dernierSegArr = (this.formVoyage.segments[this.formVoyage.segments.length - 1].villeArrivee || '').trim().toLowerCase();

    // Règle 1 : Départ et Arrivée globaux
    if (premierSegDep !== '' && villeDepGlobale !== premierSegDep) {
      this.erreurFormulaire = "La ville de départ globale doit être identique à la ville de départ du 1er segment.";
      return;
    }
    if (dernierSegArr !== '' && villeArrGlobale !== dernierSegArr) {
      this.erreurFormulaire = "La ville d'arrivée globale doit être identique à la ville d'arrivée du dernier segment.";
      return;
    }

    // Règle 2 : Continuité entre les segments
    for (let i = 0; i < this.formVoyage.segments.length - 1; i++) {
      const arrPrecedent = (this.formVoyage.segments[i].villeArrivee || '').trim().toLowerCase();
      const depSuivant = (this.formVoyage.segments[i+1].villeDepart || '').trim().toLowerCase();
      
      if (arrPrecedent !== '' && depSuivant !== '' && arrPrecedent !== depSuivant) {
        this.erreurFormulaire = `Continuité rompue : La ville d'arrivée du Segment ${i+1} doit correspondre au départ du Segment ${i+2}.`;
        return;
      }
    }

    // ==========================================
    // ⏱️ RÈGLES DE COHÉRENCE TEMPORELLES ET STATUT
    // ==========================================

    const maintenant = new Date();

    for (let i = 0; i < this.formVoyage.segments.length; i++) {
      const seg = this.formVoyage.segments[i];
      
      if (!seg.villeDepart || !seg.villeArrivee || !seg.heureDepart || !seg.heureArrivee) {
        this.erreurFormulaire = `Segment ${i+1} : Tous les champs doivent être remplis.`;
        return;
      }

      const dep = new Date(seg.heureDepart);
      const arr = new Date(seg.heureArrivee);

      // L'arrivée doit être APRES le départ
      if (arr <= dep) {
        this.erreurFormulaire = `Segment ${i+1} : L'heure d'arrivée doit être postérieure au départ.`;
        return;
      }

      // Le départ du segment N doit être APRES l'arrivée du segment N-1
      if (i > 0) {
        const arriveePrecedente = new Date(this.formVoyage.segments[i-1].heureArrivee);
        if (dep <= arriveePrecedente) {
          this.erreurFormulaire = `Segment ${i+1} : Le départ doit se faire APRÈS l'arrivée du Segment ${i}.`;
          return;
        }
      }
    }

    // 👉 REGLE 2 : Contrôle des dates par rapport au statut sélectionné
    const premierDepart = new Date(this.formVoyage.segments[0].heureDepart);
    const derniereArrivee = new Date(this.formVoyage.segments[this.formVoyage.segments.length - 1].heureArrivee);

    if (this.formVoyage.statut === 'A_VENIR') {
      if (premierDepart <= maintenant) {
        this.erreurFormulaire = `Cohérence Statut : Pour un voyage "A VENIR", la date de départ du 1er segment doit être dans le futur (après ${maintenant.toLocaleString('fr-FR')}).`;
        return;
      }
    } 
    else if (this.formVoyage.statut === 'EN_COURS') {
      if (maintenant < premierDepart || maintenant > derniereArrivee) {
        this.erreurFormulaire = `Cohérence Statut : Pour un voyage "EN COURS", la date actuelle (${maintenant.toLocaleString('fr-FR')}) doit être comprise entre le 1er départ et la dernière arrivée.`;
        return;
      }
    } 
    else if (this.formVoyage.statut === 'TERMINE') {
      if (derniereArrivee >= maintenant) {
        this.erreurFormulaire = `Cohérence Statut : Pour un voyage "TERMINE", l'arrivée du dernier segment doit être dans le passé (avant ${maintenant.toLocaleString('fr-FR')}).`;
        return;
      }
    }
  }

  sauvegarder() {
    this.verifierFormulaire();
    if (this.erreurFormulaire !== '') return;

    const backend = this.serveurService.getBackend();
    
    const segmentsFormates = this.formVoyage.segments.map((s: any, index: number) => {
      return backend === 'spring' ? {
        ordre: index + 1, villeDepart: s.villeDepart, villeArrivee: s.villeArrivee, heureDepart: s.heureDepart, heureArrivee: s.heureArrivee
      } : {
        ordre: index + 1, ville_depart: s.villeDepart, ville_arrivee: s.villeArrivee, heure_depart: s.heureDepart, heure_arrivee: s.heureArrivee
      };
    });

    const payload = backend === 'spring' ? {
      villeDepart: this.formVoyage.villeDepart, villeArrivee: this.formVoyage.villeArrivee,
      prixTotal: Number(this.formVoyage.prixTotal), nombrePlacesTotal: Number(this.formVoyage.nombrePlacesTotal),
      statut: this.formVoyage.statut, segments: segmentsFormates
    } : {
      ville_depart: this.formVoyage.villeDepart, ville_arrivee: this.formVoyage.villeArrivee,
      prix_total: Number(this.formVoyage.prixTotal), nombre_places_total: Number(this.formVoyage.nombrePlacesTotal),
      statut: this.formVoyage.statut, segments: segmentsFormates
    };

    const requete = this.voyageId 
      ? this.voyageService.modifierVoyage(this.voyageId, payload)
      : this.voyageService.creerVoyage(payload);

    requete.subscribe({
      next: () => this.router.navigate(['/admin/voyages']),
      error: () => alert("Erreur lors de la sauvegarde du voyage.")
    });
  }

  annuler() { 
    this.router.navigate(['/admin/voyages']); 
  }
}
<div class="form-page-container">
  
  <div class="header-action">
    <h2>{{ voyageId ? 'Modifier le Voyage' : 'Nouveau Voyage' }}</h2>
    <button class="btn-back" (click)="annuler()">
      <span>⬅</span> Retour à la liste
    </button>
  </div>

  @if (isLoading) {
    <div style="text-align: center; padding: 50px;">
      <p>⏳ Chargement des données techniques...</p>
    </div>
  } @else {
    <div class="card-form">
      
      <div class="form-row">
        <div class="form-group">
          <label>Ville de Départ</label>
          <input type="text" [(ngModel)]="formVoyage.villeDepart" (ngModelChange)="verifierFormulaire()" placeholder="Ex: Paris">
        </div>
        <div class="form-group">
          <label>Ville d'Arrivée</label>
          <input type="text" [(ngModel)]="formVoyage.villeArrivee" (ngModelChange)="verifierFormulaire()" placeholder="Ex: New York">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label>Prix Total (€)</label>
          <input type="number" [(ngModel)]="formVoyage.prixTotal" (ngModelChange)="verifierFormulaire()" placeholder="0.00">
        </div>
        <div class="form-group">
          <label>Nombre de Places</label>
          <input type="number" [(ngModel)]="formVoyage.nombrePlacesTotal" (ngModelChange)="verifierFormulaire()" placeholder="Ex: 150">
        </div>
        <div class="form-group">
          <label>Statut</label>
          <select [(ngModel)]="formVoyage.statut" [disabled]="!voyageId">
            <option value="A_VENIR">A VENIR</option>
            <option *ngIf="voyageId" value="EN_COURS">EN COURS</option>
            <option *ngIf="voyageId" value="TERMINE">TERMINE</option>
            <option *ngIf="voyageId" value="ANNULE">ANNULE</option>
          </select>
        </div>
      </div>

      <div class="segments-box">
        <div class="segments-header">
          <label>🧩 Étapes du trajet (Segments)</label>
          <button class="btn-add-segment" (click)="ajouterSegment()">+ Ajouter une escale</button>
        </div>
        
        <div class="segments-list">
          @for (seg of formVoyage.segments; track $index) {
            <div class="segment-card">
              <div class="segment-title">
                <span class="segment-number">SEGMENT {{ $index + 1 }}</span>
                <button class="btn-delete-segment" (click)="supprimerSegment($index)">Supprimer</button>
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label>Ville Départ</label>
                  <input type="text" [(ngModel)]="seg.villeDepart" (ngModelChange)="verifierFormulaire()" placeholder="Départ">
                </div>
                <div class="form-group">
                  <label>Date & Heure Départ</label>
                  <input type="datetime-local" [(ngModel)]="seg.heureDepart" (ngModelChange)="verifierFormulaire()">
                </div>
              </div>

              <div class="form-row" style="margin-bottom: 0;">
                <div class="form-group">
                  <label>Ville Arrivée</label>
                  <input type="text" [(ngModel)]="seg.villeArrivee" (ngModelChange)="verifierFormulaire()" placeholder="Arrivée">
                </div>
                <div class="form-group">
                  <label>Date & Heure Arrivée</label>
                  <input type="datetime-local" [(ngModel)]="seg.heureArrivee" (ngModelChange)="verifierFormulaire()">
                </div>
              </div>
            </div>
          }
        </div>
      </div>

      @if (erreurFormulaire) {
        <div class="alert-box error">
          <span>⚠️</span> {{ erreurFormulaire }}
        </div>
      }

      <div class="form-actions">
        <button class="btn-cancel" (click)="annuler()">Annuler</button>
        <button class="btn-save" [disabled]="erreurFormulaire !== ''" (click)="sauvegarder()">
          {{ voyageId ? '💾 Enregistrer les modifications' : '🚀 Créer le voyage' }}
        </button>
      </div>

    </div>
  }
</div>
