// react/agence-de-voyage-react/src/components/inscription/Inscription.tsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { AuthService } from '../../services/auth.service';
import './Inscription.css';

export const InscriptionComponent = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({ email: '', motDePasse: '' });
  const [messageErreur, setMessageErreur] = useState('');
  const [hidePassword, setHidePassword] = useState(true);
  const [isLoading, setIsLoading] = useState(false);

  const togglePasswordVisibility = () => {
    setHidePassword(!hidePassword);
  };

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (isLoading) return; 

    setIsLoading(true);
    setMessageErreur('');
    
    AuthService.register(formData)
      .then(() => {
        return AuthService.login(formData.email, formData.motDePasse);
      })
      .then(() => {
        setIsLoading(false);
        navigate('/recherche');
      })
      .catch((err) => {
        setIsLoading(false);
        setMessageErreur(err.error?.error || "Erreur lors de l'inscription.");
      });
  };

  return (
    <div className="inscription-container">
      <div className="inscription-box">
        <h2>Créer un compte</h2>

        {messageErreur && <div className="alert error">{messageErreur}</div>}

        <form onSubmit={onSubmit}>
          <div className="form-group">
            <label htmlFor="email">Adresse Email</label>
            <input 
              type="email" 
              id="email" 
              name="email" 
              value={formData.email} 
              onChange={e => setFormData({...formData, email: e.target.value})} 
              placeholder="votre@email.com" 
              required 
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Mot de passe</label>
            <div className="password-wrapper">
              <input 
                type={hidePassword ? 'password' : 'text'} 
                id="password" 
                name="password" 
                value={formData.motDePasse} 
                onChange={e => setFormData({...formData, motDePasse: e.target.value})} 
                placeholder="••••••••" 
                required
              />
              <button type="button" className="btn-eye" onClick={togglePasswordVisibility}>
                {hidePassword ? '👁️' : '🙈'}
              </button>
            </div>
          </div>

          <button type="submit" className="btn-submit" disabled={isLoading}>
            {!isLoading && <span>S'inscrire</span>}
            {isLoading && <span>Création en cours...</span>}
          </button>

          <div className="toggle-mode">
            Déjà un compte ? <Link to="/login">Connectez-vous ici</Link>
          </div>
        </form>
      </div>
    </div>
  );
};

// angular/agence-voyage/src/app/components/inscription/inscription.component.ts
import { Component, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-inscription',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './inscription.component.html',
  styleUrls: ['./inscription.component.css']
})
export class InscriptionComponent {
  private authService = inject(AuthService);
  private router = inject(Router);
  private cdr = inject(ChangeDetectorRef);

  formData = { email: '', motDePasse: '' };
  messageErreur = '';
  hidePassword = true; // 👉 NOUVEAU

  togglePasswordVisibility() { // 👉 NOUVEAU
    this.hidePassword = !this.hidePassword;
  }

  onSubmit() {
    this.messageErreur = '';
    this.authService.register(this.formData).subscribe({
      next: () => {
        this.authService.login(this.formData.email, this.formData.motDePasse).subscribe({
          next: () => this.router.navigate(['/recherche']),
          error: () => this.router.navigate(['/login'])
        });
      },
      error: (err) => {
        this.messageErreur = err.error?.error || "Erreur lors de l'inscription.";
        this.cdr.detectChanges();
      }
    });
  }
}
<div class="inscription-container">
  <div class="inscription-box">
    <h2>Créer un compte</h2>

    <div *ngIf="messageErreur" class="alert error">{{ messageErreur }}</div>

    <form (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="email">Adresse Email</label>
        <input type="email" id="email" name="email" [(ngModel)]="formData.email" placeholder="votre@email.com" required>
      </div>

      <div class="form-group">
        <label for="password">Mot de passe</label>
        <div class="password-wrapper">
          <input 
            [type]="hidePassword ? 'password' : 'text'" 
            id="password" 
            name="password" 
            [(ngModel)]="formData.motDePasse" 
            placeholder="••••••••" 
            required
          >
          <button type="button" class="btn-eye" (click)="togglePasswordVisibility()">
            {{ hidePassword ? '👁️' : '🙈' }}
          </button>
        </div>
      </div>

      <button type="submit" class="btn-submit">S'inscrire</button>

      <div class="toggle-mode">
        Déjà un compte ? <a routerLink="/login">Connectez-vous ici</a>
      </div>
    </form>
  </div>
</div>
