// angular/agence-voyage/src/app/components/admin-utilisateur-form/admin-utilisateur-form.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { UtilisateurService } from '../../services/utilisateur.service';

@Component({
  selector: 'app-admin-utilisateur-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-utilisateur-form.component.html',
  styleUrls: ['../admin-voyages/admin-voyages.component.css'] 
})
export class AdminUtilisateurFormComponent implements OnInit {
  private utilisateurService = inject(UtilisateurService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private cdr = inject(ChangeDetectorRef);

  utilisateurId!: number;
  isLoading = true;
  formUtilisateur = { role: 'ROLE_USER' };

  ngOnInit() {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.utilisateurId = Number(idParam);
      this.chargerUtilisateur();
    }
  }

  chargerUtilisateur() {
    this.utilisateurService.getUn(this.utilisateurId).subscribe({
      next: (data: any) => {
        this.formUtilisateur = {
          role: data.role || 'ROLE_USER'
        };
        this.isLoading = false;
        this.cdr.detectChanges(); 
      },
      error: () => {
        this.isLoading = false;
        this.cdr.detectChanges();
        alert("Erreur lors de la récupération de l'utilisateur.");
        this.retour();
      }
    });
  }

  sauvegarder() {
    this.utilisateurService.modifier(this.utilisateurId, this.formUtilisateur).subscribe({
      next: () => {
        alert("✅ Utilisateur modifié avec succès.");
        this.retour();
      },
      error: () => alert("❌ Erreur lors de la modification.")
    });
  }

  retour() {
    this.router.navigate(['/admin/utilisateurs']);
  }
}
<div class="crud-section">
  <div class="section-header" style="justify-content: flex-start; gap: 20px;">
    <button class="btn-action" style="padding: 10px; border-radius: 5px; font-weight: bold;" (click)="retour()">⬅ Retour</button>
    <h3>Modification Utilisateur #{{ utilisateurId }}</h3>
  </div>

  @if (isLoading) {
    <p>Chargement des données de l'utilisateur...</p>
  } @else {
    <div style="max-width: 500px; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
      
      <div style="margin-bottom: 30px;">
        <label style="display: block; font-weight: bold; margin-bottom: 8px;">Rôle d'accès :</label>
        <select [(ngModel)]="formUtilisateur.role" style="width: 100%; padding: 10px; border: 1px solid #cbd5e1; border-radius: 6px;">
          <option value="ROLE_USER">Utilisateur Simple (ROLE_USER)</option>
          <option value="ROLE_ADMIN">Administrateur (ROLE_ADMIN)</option>
        </select>
      </div>

      <div style="display: flex; justify-content: flex-end; gap: 10px;">
        <button class="btn-action btn-delete" (click)="retour()">Annuler</button>
        <button class="btn-add" (click)="sauvegarder()">💾 Sauvegarder</button>
      </div>
    </div>
  }
</div>

// react/agence-de-voyage-react/src/components/admin-utilisateur-form/AdminUtilisateurForm.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { UtilisateurService } from '../../services/utilisateur.service';
import '../admin-voyages/AdminVoyages.css';

export const AdminUtilisateurFormComponent = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [formUtilisateur, setFormUtilisateur] = useState({ role: 'ROLE_USER' });
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    UtilisateurService.getUn(Number(id)).then(data => {
      setFormUtilisateur({ role: data.role || 'ROLE_USER' });
      setIsLoading(false);
    }).catch(() => {
      alert("Erreur lors de la récupération de l'utilisateur.");
      navigate(-1);
    });
  }, [id, navigate]);

  const sauvegarder = () => {
    UtilisateurService.modifier(Number(id), formUtilisateur).then(() => {
      alert("✅ Utilisateur modifié avec succès.");
      navigate(-1);
    }).catch(() => alert("Erreur lors de la modification."));
  };

  const retour = () => navigate(-1);

  // 👉 CORRECTION : Structure HTML strictement identique à l'Angular pour appliquer le CSS
  return (
    <div className="crud-section">
      <div className="section-header" style={{ justifyContent: 'flex-start', gap: '20px' }}>
        <button className="btn-action" style={{ padding: '10px', borderRadius: '5px', fontWeight: 'bold' }} onClick={retour}>⬅ Retour</button>
        <h3>Modification Utilisateur #{id}</h3>
      </div>

      {isLoading ? (
        <p>Chargement des données de l'utilisateur...</p>
      ) : (
        <div style={{ maxWidth: '500px', background: 'white', padding: '30px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)' }}>
          
          <div style={{ marginBottom: '30px' }}>
            <label style={{ display: 'block', fontWeight: 'bold', marginBottom: '8px' }}>Rôle d'accès :</label>
            <select 
              value={formUtilisateur.role} 
              onChange={e => setFormUtilisateur({ role: e.target.value })} 
              style={{ width: '100%', padding: '10px', border: '1px solid #cbd5e1', borderRadius: '6px' }}
            >
              <option value="ROLE_USER">Utilisateur Simple (ROLE_USER)</option>
              <option value="ROLE_ADMIN">Administrateur (ROLE_ADMIN)</option>
            </select>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
            <button className="btn-action btn-delete" onClick={retour}>Annuler</button>
            <button className="btn-add" onClick={sauvegarder}>💾 Sauvegarder</button>
          </div>

        </div>
      )}
    </div>
  );
};
