// angular/agence-voyage/src/app/components/admin-recherche-place/admin-recherche-place.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { VoyageService } from '../../services/voyage.service';
import { BilletService } from '../../services/billet.service';
import { Voyage } from '../../models/voyage';
import { Reservation } from '../../models/reservation';

@Component({
  selector: 'app-admin-recherche-place',
  standalone: true,
  imports: [CommonModule, FormsModule, CurrencyPipe],
  templateUrl: './admin-recherche-place.component.html',
  styleUrls: ['./admin-recherche-place.component.css']
})
export class AdminRecherchePlaceComponent implements OnInit {
  private voyageService = inject(VoyageService);
  private billetService = inject(BilletService);

  voyages: Voyage[] = [];
  voyageIdSelectionne: number | '' = '';
  siegeSaisi: string = '';

  resultatReservation: Reservation | null = null;
  erreurRecherche: string = '';
  isLoading: boolean = false;

  ngOnInit() {
    // On charge tous les voyages pour peupler la liste déroulante
    this.voyageService.getTousLesVoyages().subscribe({
      next: (data) => this.voyages = data,
      error: (err) => console.error("Erreur chargement voyages", err)
    });
  }

  lancerRecherche() {
    if (!this.voyageIdSelectionne || !this.siegeSaisi.trim()) {
      return;
    }

    this.isLoading = true;
    this.erreurRecherche = '';
    this.resultatReservation = null;

    // On s'assure que le siège est en majuscules (ex: 12a -> 12A)
    const siegeFormatte = this.siegeSaisi.trim().toUpperCase();

    this.billetService.trouverReservationParSiege(Number(this.voyageIdSelectionne), siegeFormatte).subscribe({
      next: (reservation) => {
        this.resultatReservation = reservation;
        this.isLoading = false;
      },
      error: (err) => {
        this.isLoading = false;
        this.erreurRecherche = `Aucun passager n'a été trouvé à la place ${siegeFormatte} pour ce vol.`;
      }
    });
  }

  // 🛡️ Méthodes de lecture compatibles Spring/Django
  getVilleDepart(v: any): string { return v?.villeDepart || v?.ville_depart || '?'; }
  getVilleArrivee(v: any): string { return v?.villeArrivee || v?.ville_arrivee || '?'; }
  getPrixPaye(res: Reservation): number { return res.prixPaye || (res as any).prix_paye || 0; }
  getDateConfirmation(res: Reservation): string { return res.dateConfirmation || (res as any).date_confirmation || ''; }
  getEmailUtilisateur(res: Reservation): string { 
    return (res.utilisateur as any)?.email || 'Utilisateur introuvable'; 
  }
}
<div class="admin-recherche-container">
  
  <div class="header-admin">
    <h2>🕵️ Contrôle des Passagers</h2>
    <p>Recherchez à qui appartient un siège dans un vol spécifique.</p>
  </div>

  <div class="search-box">
    
    <div class="input-group">
      <label>1. Sélectionner le Voyage</label>
      <select [(ngModel)]="voyageIdSelectionne">
        <option value="">-- Choisissez un vol --</option>
        @for (voyage of voyages; track voyage.id) {
          <option [value]="voyage.id">
            Vol #{{ voyage.id }} : {{ getVilleDepart(voyage) }} ➔ {{ getVilleArrivee(voyage) }}
          </option>
        }
      </select>
    </div>

    <div class="input-group">
      <label>2. Numéro du Siège</label>
      <input type="text" [(ngModel)]="siegeSaisi" placeholder="Ex: 12A" (keyup.enter)="lancerRecherche()" />
    </div>

    <button class="btn-rechercher" 
            (click)="lancerRecherche()" 
            [disabled]="!voyageIdSelectionne || !siegeSaisi || isLoading">
      @if (isLoading) {
        ⏳ Recherche...
      } @else {
        🔍 Rechercher
      }
    </button>
  </div>

  @if (erreurRecherche) {
    <div class="alert-error">
      {{ erreurRecherche }}
    </div>
  }

  @if (resultatReservation) {
    <div class="result-card">
      <div class="result-header">
        <span class="badge-success">Passager identifié</span>
        <strong>Place : <span class="siege-highlight">{{ siegeSaisi | uppercase }}</span></strong>
      </div>

      <div class="result-body">
        <div class="info-row">
          <span class="label">Identité (Email) :</span>
          <span class="valeur text-email">{{ getEmailUtilisateur(resultatReservation) }}</span>
        </div>
        
        <div class="info-row">
          <span class="label">Réservation rattachée :</span>
          <span class="valeur">N° {{ resultatReservation.id }}</span>
        </div>

        <div class="info-row">
          <span class="label">Statut du billet :</span>
          <span class="valeur badge-statut" [class.annule]="resultatReservation.statut === 'ANNULE'">
            {{ resultatReservation.statut }}
          </span>
        </div>

        <div class="info-row">
          <span class="label">Prix d'achat (Total) :</span>
          <span class="valeur">{{ getPrixPaye(resultatReservation) | currency:'EUR':'symbol':'1.0-2' }}</span>
        </div>
      </div>
    </div>
  }

</div>

// react/agence-de-voyage-react/src/components/admin-recherche-place/AdminRecherchePlace.tsx
import React, { useState, useEffect } from 'react';
import { VoyageService } from '../../services/voyage.service';
import { BilletService } from '../../services/billet.service';
import './AdminRecherchePlace.css';

export const AdminRecherchePlaceComponent = () => {
  const [voyages, setVoyages] = useState<any[]>([]);
  const [voyageIdSelectionne, setVoyageIdSelectionne] = useState('');
  const [siegeSaisi, setSiegeSaisi] = useState('');
  const [resultat, setResultat] = useState<any>(null);
  const [erreur, setErreur] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    VoyageService.getTousLesVoyages().then(setVoyages);
  }, []);

  const lancerRecherche = () => {
    setIsLoading(true);
    setErreur('');
    BilletService.trouverReservationParSiege(Number(voyageIdSelectionne), siegeSaisi.toUpperCase())
      .then(setResultat)
      .catch(() => setErreur("Passager introuvable."))
      .finally(() => setIsLoading(false));
  };

  return (
    <div className="admin-recherche-container">
      <h2>🕵️ Contrôle des Passagers</h2>
      <div className="search-box">
        <select value={voyageIdSelectionne} onChange={e => setVoyageIdSelectionne(e.target.value)}>
          <option value="">Choisir un vol</option>
          {voyages.map(v => <option key={v.id} value={v.id}>Vol #{v.id}</option>)}
        </select>
        <input value={siegeSaisi} onChange={e => setSiegeSaisi(e.target.value)} placeholder="12A" />
        <button onClick={lancerRecherche} disabled={isLoading}>🔍 Rechercher</button>
      </div>
      {erreur && <div className="alert-error">{erreur}</div>}
      {resultat && <div>Passager trouvé : {resultat.id}</div>}
    </div>
  );
};
