// angular/agence-voyage/src/app/components/password-reset/password-reset.component.ts
import { Component, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { RouterModule } from '@angular/router';
import { ServeurService } from '../../services/serveur.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-password-reset',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './password-reset.component.html',
  styleUrls: ['./password-reset.component.css']
})
export class PasswordResetComponent {
  private http = inject(HttpClient);
  private serveurService = inject(ServeurService);
  private authService = inject(AuthService); // Pour récupérer l'URL de base proprement
  private cdr = inject(ChangeDetectorRef); // 👉 Le "marteau" pour forcer l'affichage

  email = '';
  messageErreur = '';
  messageSucces = '';
  isLoading = false;
  afficherBoutonInscription = false;

  demanderMotDePasse() {
    if (!this.email) return;
    
    this.isLoading = true;
    this.messageErreur = '';
    this.messageSucces = '';
    this.afficherBoutonInscription = false;

    // Récupération propre de l'URL (ex: http://localhost:8080/api)
    const baseUrl = this.authService.getBaseUrl(); 
    const isDjango = baseUrl.includes('8000');
    
    // 👉 CORRECTION : On évite de doubler le "/api/" qui causait l'erreur 401 sur Spring !
    const url = isDjango ? `${baseUrl}/auth/check-email/` : `${baseUrl}/auth/check-email`;
    
    this.http.post(url, { email: this.email }).subscribe({
      next: () => {
        this.isLoading = false;
        // Le message s'affichera dans l'encadré vert grâce à la classe .success de ton CSS
        this.messageSucces = "✅ Un e-mail contenant votre mot de passe vient de vous être envoyé ! Vérifiez votre boîte de réception.";
        this.cdr.detectChanges(); // 👉 Force Angular à afficher le message vert immédiatement
      },
      error: () => {
        this.isLoading = false;
        this.messageErreur = "Cette adresse e-mail n'est pas reconnue dans notre base de données.";
        this.afficherBoutonInscription = true;
        this.cdr.detectChanges(); // 👉 Force Angular à afficher l'erreur immédiatement
      }
    });
  }

  reessayer() {
    this.afficherBoutonInscription = false;
    this.messageErreur = '';
    this.email = '';
    this.cdr.detectChanges();
  }
}
<div class="reset-container">
  <div class="reset-box">
    <h2>Mot de passe oublié</h2>

    <div *ngIf="messageErreur" class="alert error">{{ messageErreur }}</div>
    <div *ngIf="messageSucces" class="alert success">{{ messageSucces }}</div>

    <form *ngIf="!messageSucces && !afficherBoutonInscription" (ngSubmit)="demanderMotDePasse()">
      <p class="description">Entrez votre adresse e-mail. Si elle est reconnue, nous vous enverrons votre mot de passe actuel.</p>
      
      <div class="form-group">
        <label>Adresse Email</label>
        <input type="email" [(ngModel)]="email" name="email" placeholder="votre@email.com" required [disabled]="isLoading">
      </div>
      
      <button type="submit" class="btn-submit" [disabled]="isLoading">
        {{ isLoading ? 'Recherche en cours...' : 'Recevoir mon mot de passe' }}
      </button>
      
      <div class="links">
        <a routerLink="/login">Retour à la connexion</a>
      </div>
    </form>

    <div *ngIf="afficherBoutonInscription" class="not-found-zone">
      <p class="description" style="color: #ef4444; font-weight: bold;">Souhaitez-vous créer un compte ?</p>
      <button routerLink="/inscription" class="btn-submit btn-register">Aller à l'inscription</button>
      <div class="links"><a (click)="reessayer()">Réessayer avec une autre adresse</a></div>
    </div>

    <div *ngIf="messageSucces" class="links" style="margin-top: 25px;">
      <button routerLink="/login" class="btn-submit">Retourner à la page de connexion</button>
    </div>
    
  </div>
</div>

// react/agence-de-voyage-react/src/components/password-reset/PasswordReset.tsx
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { AuthService } from '../../services/auth.service';
import './PasswordReset.css';

export const PasswordResetComponent = () => {
  const [email, setEmail] = useState('');
  const [messageErreur, setMessageErreur] = useState('');
  const [messageSucces, setMessageSucces] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [afficherBoutonInscription, setAfficherBoutonInscription] = useState(false);

  const demanderMotDePasse = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;
    
    setIsLoading(true);
    setMessageErreur('');
    setMessageSucces('');
    setAfficherBoutonInscription(false);

    const baseUrl = AuthService.getBaseUrl(); 
    const isDjango = baseUrl.includes('8000');
    
    const url = isDjango ? `${baseUrl}/auth/check-email/` : `${baseUrl}/auth/check-email`;
    
    fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email })
    })
    .then(res => {
      if (!res.ok) throw res;
      setIsLoading(false);
      setMessageSucces("✅ Un e-mail contenant votre mot de passe vient de vous être envoyé ! Vérifiez votre boîte de réception.");
    })
    .catch(() => {
      setIsLoading(false);
      setMessageErreur("Cette adresse e-mail n'est pas reconnue dans notre base de données.");
      setAfficherBoutonInscription(true);
    });
  };

  const reessayer = () => {
    setAfficherBoutonInscription(false);
    setMessageErreur('');
    setEmail('');
  };

  return (
    <div className="reset-container">
      <div className="reset-box">
        <h2>Mot de passe oublié</h2>

        {messageErreur && <div className="alert error">{messageErreur}</div>}
        {messageSucces && <div className="alert success">{messageSucces}</div>}

        {!messageSucces && !afficherBoutonInscription && (
          <form onSubmit={demanderMotDePasse}>
            <p className="description">Entrez votre adresse e-mail. Si elle est reconnue, nous vous enverrons votre mot de passe actuel.</p>
            
            <div className="form-group">
              <label>Adresse Email</label>
              <input 
                type="email" 
                value={email} 
                onChange={(e) => setEmail(e.target.value)} 
                name="email" 
                placeholder="votre@email.com" 
                required 
                disabled={isLoading} 
              />
            </div>
            
            <button type="submit" className="btn-submit" disabled={isLoading}>
              {isLoading ? 'Recherche en cours...' : 'Recevoir mon mot de passe'}
            </button>
            
            <div className="links">
              <Link to="/login">Retour à la connexion</Link>
            </div>
          </form>
        )}

        {afficherBoutonInscription && (
          <div className="not-found-zone">
            <p className="description" style={{ color: '#ef4444', fontWeight: 'bold' }}>Souhaitez-vous créer un compte ?</p>
            <Link to="/inscription">
              <button className="btn-submit btn-register">Aller à l'inscription</button>
            </Link>
            <div className="links"><a onClick={reessayer}>Réessayer avec une autre adresse</a></div>
          </div>
        )}

        {messageSucces && (
          <div className="links" style={{ marginTop: '25px' }}>
            <Link to="/login">
              <button className="btn-submit">Retourner à la page de connexion</button>
            </Link>
          </div>
        )}
      </div>
    </div>
  );
};
