// react/agence-de-voyage-react/src/components/AdminUtilisateurs/AdminUtilisateurs.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { UtilisateurService } from '../../services/utilisateur.service';
import { AuthService } from '../../services/auth.service';
import '../admin-voyages/AdminVoyages.css'; 

export const AdminUtilisateursComponent = () => {
  const navigate = useNavigate();
  const [utilisateurs, setUtilisateurs] = useState<any[]>([]);
  const idAdminActuel = AuthService.getUserId();

  const [texteRecherche, setTexteRecherche] = useState('');
  const [filtreEmail, setFiltreEmail] = useState('');
  const [filtreRole, setFiltreRole] = useState('');
  const [filtreDateInscription, setFiltreDateInscription] = useState('');

  const [critereTri, setCritereTri] = useState('id');
  const [triAscendant, setTriAscendant] = useState(true);

  useEffect(() => {
    chargerUtilisateurs();
  }, []);

  const chargerUtilisateurs = () => {
    UtilisateurService.getTous()
      .then((data: any) => {
        const donneesBrutes = data?.results || data?.content || data?._embedded?.utilisateurs || data;
        const listeComplete = Array.isArray(donneesBrutes) ? donneesBrutes : [];
        // On cache l'admin actuel de la liste
        setUtilisateurs(listeComplete.filter(u => u.id !== idAdminActuel));
      })
      .catch((err) => {
        if (err.status === 404 || err.status === 204) setUtilisateurs([]);
        else alert('Erreur lors du chargement des utilisateurs.');
      });
  };

  const supprimerUtilisateur = (id: number) => {
    if (id === idAdminActuel) {
      alert("Vous ne pouvez pas supprimer votre propre compte admin.");
      return;
    }
    if (window.confirm("Êtes-vous sûr de vouloir bannir et supprimer cet utilisateur ? Cette action détruira aussi son historique et ses réservations.")) {
      UtilisateurService.supprimer(id)
        .then(() => {
          alert("✅ Utilisateur banni et supprimé.");
          chargerUtilisateurs();
        })
        .catch(() => alert("Erreur lors de la suppression."));
    }
  };

  const modifierUtilisateur = (id: number) => navigate(`/admin/utilisateurs/${id}/modifier`);
  const voirReservationsUtilisateur = (id: number) => navigate(`/admin/utilisateurs/${id}/reservations`);
  const voirAvisUtilisateur = (id: number) => navigate(`/admin/utilisateurs/${id}/avis`);

  const changerTri = (critere: string) => {
    if (critereTri === critere) setTriAscendant(!triAscendant);
    else { setCritereTri(critere); setTriAscendant(true); }
  };

  const getUtilisateursFiltres = () => {
    let resultats = utilisateurs.filter(u => {
      const email = (u.email || '').toLowerCase();
      const role = (u.role || '').toLowerCase();
      const rechercheGlobale = texteRecherche.toLowerCase();

      const matchGlobal = !texteRecherche || email.includes(rechercheGlobale) || role.includes(rechercheGlobale) || u.id.toString().includes(rechercheGlobale);
      const matchEmail = !filtreEmail || email.includes(filtreEmail.toLowerCase());
      const matchRole = !filtreRole || role.includes(filtreRole.toLowerCase());
      
      let matchDate = true;
      if (filtreDateInscription) {
        const dateInscrit = u.dateInscription || u.date_inscription || '';
        matchDate = dateInscrit.startsWith(filtreDateInscription);
      }

      return matchGlobal && matchEmail && matchRole && matchDate;
    });

    resultats.sort((a, b) => {
      let valA = a[critereTri] || '';
      let valB = b[critereTri] || '';
      if (typeof valA === 'string') valA = valA.toLowerCase();
      if (typeof valB === 'string') valB = valB.toLowerCase();
      if (valA < valB) return triAscendant ? -1 : 1;
      if (valA > valB) return triAscendant ? 1 : -1;
      return 0;
    });

    return resultats;
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return 'N/A';
    return new Date(dateStr).toLocaleDateString('fr-FR', { day: '2-digit', month: '2-digit', year: 'numeric' });
  };

  const utilisateursFiltres = getUtilisateursFiltres();

  return (
    <div className="crud-section">
      <div className="section-header">
        <h3>Gestion des Comptes Utilisateurs</h3>
      </div>

      <div className="filter-row">
        <div className="filter-group">
          <label>Email exact ou partiel</label>
          <input type="text" value={filtreEmail} onChange={e => setFiltreEmail(e.target.value)} placeholder="Ex: client25@mail..." />
        </div>
        <div className="filter-group">
          <label>Rôle</label>
          <select value={filtreRole} onChange={e => setFiltreRole(e.target.value)}>
            <option value="">Tous les rôles</option>
            <option value="ROLE_USER">Utilisateur (USER)</option>
            <option value="ROLE_ADMIN">Administrateur (ADMIN)</option>
          </select>
        </div>
        <div className="filter-group">
          <label>Date d'inscription</label>
          <input type="date" value={filtreDateInscription} onChange={e => setFiltreDateInscription(e.target.value)} />
        </div>
        <div className="filter-group">
          <label>Recherche Rapide ID</label>
          <input type="text" value={texteRecherche} onChange={e => setTexteRecherche(e.target.value)} placeholder="Saisir un ID..." />
        </div>
      </div>
      
      <table className="admin-table">
        <thead>
          <tr>
            <th onClick={() => changerTri('id')} style={{ cursor: 'pointer' }}>ID ↕️</th>
            <th onClick={() => changerTri('email')} style={{ cursor: 'pointer' }}>Adresse Email ↕️</th>
            <th onClick={() => changerTri('role')} style={{ cursor: 'pointer' }}>Rôle ↕️</th>
            <th>Date d'inscription</th> 
            <th>Actions Administrateur</th>
          </tr>
        </thead>
        <tbody>
          {utilisateursFiltres.map((u) => (
            <tr key={u.id}>
              <td><strong>#{u.id}</strong></td>
              <td>{u.email || 'N/A'}</td>
              <td>
                {/* 👉 LA CORRECTION EST ICI : On appelle les nouvelles classes CSS */}
                <span className={`badge-statut ${u.role === 'ROLE_ADMIN' || u.role === 'ADMIN' ? 'ROLE_ADMIN' : 'ROLE_USER'}`}>
                  {u.role === 'ROLE_ADMIN' || u.role === 'ADMIN' ? 'Administrateur' : 'Utilisateur'}
                </span>
              </td>
              <td>{formatDate(u.dateInscription || u.date_inscription)}</td>
              <td className="action-cells">
                <button className="btn-action btn-edit" onClick={() => modifierUtilisateur(u.id)}>✏️ Modifier</button> 
                <button className="btn-action btn-view" onClick={() => voirReservationsUtilisateur(u.id)}>🎫 Réservations</button>
                <button className="btn-action btn-view" onClick={() => voirAvisUtilisateur(u.id)}>⭐ Modérer Avis</button>
                <button className="btn-action btn-delete" onClick={() => supprimerUtilisateur(u.id)}>🚫 Bannir</button>
              </td>
            </tr>
          ))}
          {utilisateursFiltres.length === 0 && (
            <tr>
              <td colSpan={5} style={{ textAlign: 'center', padding: '30px', color: '#64748b' }}>
                Aucun utilisateur ne correspond à vos critères de recherche.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

// angular/agence-voyage/src/app/components/admin-utilisateurs/admin-utilisateurs.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common'; // Injection DatePipe pour le HTML
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { UtilisateurService } from '../../services/utilisateur.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-admin-utilisateurs',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-utilisateurs.component.html',
  styleUrls: ['../admin-voyages/admin-voyages.component.css'] 
})
export class AdminUtilisateursComponent implements OnInit {
  private utilisateurService = inject(UtilisateurService);
  private authService = inject(AuthService);
  private router = inject(Router);

  utilisateurs: any[] = [];
  idAdminActuel = this.authService.getUserId();

  // 👉 NOUVEAUX OUTILS DE FILTRAGE
  texteRecherche: string = '';
  filtreEmail: string = '';
  filtreRole: string = '';
  filtreDateInscription: string = '';

  critereTri: string = 'id';
  triAscendant: boolean = true;

  ngOnInit() {
    this.chargerUtilisateurs();
  }

  chargerUtilisateurs() {
    this.utilisateurService.getTous().subscribe({
      next: (data: any) => {
        const donneesBrutes = data?.results || data?.content || data?._embedded?.utilisateurs || data;
        const listeComplete = Array.isArray(donneesBrutes) ? donneesBrutes : [];
        this.utilisateurs = listeComplete.filter((u: any) => u.id !== this.idAdminActuel);
      },
      error: (err) => console.error("Erreur chargement utilisateurs", err)
    });
  }

  supprimerUtilisateur(id: number) {
    if (confirm("⚠️ Bannir définitivement cet utilisateur de la plateforme ? (Cette action détruira ses données non-liées).")) {
      this.utilisateurService.supprimer(id).subscribe({
        next: () => { alert('✅ Utilisateur supprimé.'); this.chargerUtilisateurs(); },
        error: () => alert("❌ Impossible de supprimer cet utilisateur (il a peut-être des réservations en cours).")
      });
    }
  }

  voirAvisUtilisateur(id: number) { this.router.navigate(['/admin/utilisateurs', id, 'avis']); }
  voirReservationsUtilisateur(id: number) { this.router.navigate(['/admin/utilisateurs', id, 'reservations']); }
  modifierUtilisateur(id: number) { this.router.navigate(['/admin/utilisateurs', id, 'modifier']); }

  changerTri(critere: string) {
    if (this.critereTri === critere) {
      this.triAscendant = !this.triAscendant;
    } else {
      this.critereTri = critere;
      this.triAscendant = true;
    }
  }

  // 👉 LA NOUVELLE LOGIQUE DE FILTRAGE
  get utilisateursFiltres() {
    let resultats = this.utilisateurs.filter(u => {
      const email = (u.email || '').toLowerCase();
      const role = (u.role || '').toLowerCase();
      const rechercheGlobale = this.texteRecherche.toLowerCase();

      // 1. Vérification Globale
      const matchGlobal = !this.texteRecherche || 
                          email.includes(rechercheGlobale) || 
                          role.includes(rechercheGlobale) || 
                          u.id.toString().includes(rechercheGlobale);

      // 2. Vérifications Spécifiques
      const matchEmail = !this.filtreEmail || email.includes(this.filtreEmail.toLowerCase());
      const matchRole = !this.filtreRole || role.includes(this.filtreRole.toLowerCase());
      
      // 3. Vérification Date
      let matchDate = true;
      if (this.filtreDateInscription) {
        const dateInscrit = u.dateInscription || u.date_inscription || '';
        matchDate = dateInscrit.startsWith(this.filtreDateInscription);
      }

      return matchGlobal && matchEmail && matchRole && matchDate;
    });

    resultats.sort((a, b) => {
      let valA = a[this.critereTri] || '';
      let valB = b[this.critereTri] || '';
      if (typeof valA === 'string') valA = valA.toLowerCase();
      if (typeof valB === 'string') valB = valB.toLowerCase();
      if (valA < valB) return this.triAscendant ? -1 : 1;
      if (valA > valB) return this.triAscendant ? 1 : -1;
      return 0;
    });

    return resultats;
  }
}
<div class="crud-section">
  
  <div class="section-header">
    <h3>Gestion des Comptes Utilisateurs</h3>
  </div>

  <div class="filter-row">
    <div class="filter-group">
      <label>Email exact ou partiel</label>
      <input type="text" [(ngModel)]="filtreEmail" placeholder="Ex: client25@mail...">
    </div>
    <div class="filter-group">
      <label>Rôle</label>
      <select [(ngModel)]="filtreRole">
        <option value="">Tous les rôles</option>
        <option value="ROLE_USER">Utilisateur (USER)</option>
        <option value="ROLE_ADMIN">Administrateur (ADMIN)</option>
      </select>
    </div>
    <div class="filter-group">
      <label>Date d'inscription</label>
      <input type="date" [(ngModel)]="filtreDateInscription">
    </div>
    <div class="filter-group">
      <label>Recherche Rapide ID</label>
      <input type="text" [(ngModel)]="texteRecherche" placeholder="Saisir un ID...">
    </div>
  </div>
  
  <table class="admin-table">
    <thead>
      <tr>
        <th (click)="changerTri('id')" style="cursor: pointer;">ID ↕️</th>
        <th (click)="changerTri('email')" style="cursor: pointer;">Adresse Email ↕️</th>
        <th (click)="changerTri('role')" style="cursor: pointer;">Rôle ↕️</th>
        <th>Date d'inscription</th> <th>Actions Administrateur</th>
      </tr>
    </thead>
    <tbody>
      @for (u of utilisateursFiltres; track u.id) {
        <tr>
          <td><strong>#{{ u.id }}</strong></td>
          <td>{{ u.email || 'N/A' }}</td>
          <td>
            <span class="badge-statut" [ngClass]="u.role === 'ROLE_ADMIN' ? 'TERMINE' : 'A_VENIR'">
              {{ u.role || 'ROLE_USER' }}
            </span>
          </td>
          <td>{{ (u.dateInscription || u.date_inscription) ? ((u.dateInscription || u.date_inscription) | date:'dd/MM/yyyy') : 'N/A' }}</td>
          <td class="action-cells">
            <button class="btn-action btn-edit" (click)="modifierUtilisateur(u.id)">✏️ Modifier</button> 
            <button class="btn-action btn-view" (click)="voirReservationsUtilisateur(u.id)">🎫 Réservations</button>
            <button class="btn-action btn-view" (click)="voirAvisUtilisateur(u.id)">⭐ Modérer Avis</button>
            <button class="btn-action btn-delete" (click)="supprimerUtilisateur(u.id)">🚫 Bannir</button>
          </td>
        </tr>
      }
      @if (utilisateursFiltres.length === 0) {
        <tr><td colspan="5" style="text-align: center; color: #94a3b8; padding: 25px;">Aucun utilisateur trouvé.</td></tr>
      }
    </tbody>
  </table>
</div>
