// angular/agence-voyage/src/app/components/avis-form/avis-form.component.ts
import { Component, EventEmitter, Input, Output, inject, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { VoyageService } from '../../services/voyage.service';
import { AudioRecorderService } from '../../services/audio-recorder.service';

@Component({
  selector: 'app-avis-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './avis-form.component.html',
  styleUrls: ['./avis-form.component.css']
})
export class AvisFormComponent implements OnInit {
  @Input() reservationId!: number;
  @Input() avisExistant: any = null;

  @Output() fermer = new EventEmitter<void>();
  @Output() avisSoumis = new EventEmitter<void>();

  private voyageService = inject(VoyageService);
  private audioRecorderService = inject(AudioRecorderService);
  private cdr = inject(ChangeDetectorRef); // 👉 CORRECTION : Indispensable pour débloquer l'interface

  note: number = 5;
  commentaire: string = '';
  
  isLoadingText: boolean = false;
  isRecording: boolean = false;
  isLoadingAudio: boolean = false;
  erreur: string = '';

  ngOnInit() {
    if (this.avisExistant) {
      this.note = this.avisExistant.note;
      this.commentaire = this.avisExistant.commentaire || '';
    }
  }

  setNote(valeur: number) {
    this.note = valeur;
  }

  soumettreTexte() {
    this.isLoadingText = true;
    this.erreur = '';

    const requete = this.avisExistant
      ? this.voyageService.modifierAvis(this.avisExistant.id, this.note, this.commentaire)
      : this.voyageService.creerAvisTexte(this.reservationId, this.note, this.commentaire);

    requete.subscribe({
      next: () => {
        this.isLoadingText = false;
        this.avisSoumis.emit(); 
      },
      error: (err) => {
        this.isLoadingText = false;
        this.gererErreurIA(err); // 👉 NOUVEAU : Centralisation des messages
        this.cdr.detectChanges(); 
      }
    });
  }

  async toggleEnregistrement() {
    this.erreur = '';

    if (this.isRecording) {
      this.isRecording = false;
      this.isLoadingAudio = true;
      this.cdr.detectChanges();

      try {
        const audioBlob = await this.audioRecorderService.stopRecording();
        const idPourModif = this.avisExistant ? this.avisExistant.id : undefined;
        
        this.voyageService.soumettreAvisVocal(this.reservationId, audioBlob, this.note, idPourModif).subscribe({
          next: () => {
            this.isLoadingAudio = false;
            this.avisSoumis.emit();
          },
          error: (err) => {
            this.isLoadingAudio = false;
            this.gererErreurIA(err); // 👉 NOUVEAU
            this.cdr.detectChanges(); // 👉 CORRECTION : Débloque le spinner
          }
        });
      } catch (err) {
        this.isLoadingAudio = false;
        this.erreur = "Erreur lors de l'arrêt du micro.";
        this.cdr.detectChanges();
      }
    } else {
      try {
        await this.audioRecorderService.startRecording();
        this.isRecording = true;
        this.cdr.detectChanges();
      } catch (err) {
        this.erreur = "L'accès au microphone a été refusé.";
        this.cdr.detectChanges();
      }
    }
  }

  // 👉 NOUVEAU : Traduction humaine des codes d'erreur
  private gererErreurIA(err: any) {
    if (err.status === 429) {
      this.erreur = "L'IA est actuellement saturée (trop de requêtes). Veuillez patienter quelques instants.";
    } else if (err.status === 503) {
      this.erreur = "Le service IA est temporairement indisponible.";
    } else if (err.status === 405) {
      this.erreur = "Action refusée par le serveur (Erreur de configuration 405).";
    } else {
      this.erreur = "Une erreur est survenue lors du traitement : " + (err.error?.detail || err.message);
    }
  }
}
<div class="modal-overlay" (click)="fermer.emit()">
  <div class="modal-content" (click)="$event.stopPropagation()">
    
    <div class="modal-header">
      <h3>{{ avisExistant ? 'Modifier mon avis' : 'Donner mon avis' }}</h3>
      <button class="btn-close" (click)="fermer.emit()">✖</button>
    </div>

    <div class="modal-body">
      
      <!-- La sélection de la note -->
      <div class="rating-section">
        <p class="label">Notez votre voyage :</p>
        <div class="stars">
          @for (star of [1, 2, 3, 4, 5]; track star) {
            <span class="star" 
                  [class.active]="star <= note" 
                  (click)="setNote(star)">
              ★
            </span>
          }
        </div>
      </div>

      <!-- La zone de texte libre -->
      <div class="form-group">
        <p class="label">Votre commentaire (optionnel si vocal) :</p>
        <textarea 
          [(ngModel)]="commentaire" 
          rows="4" 
          placeholder="Racontez votre expérience..."
          [disabled]="isRecording || isLoadingAudio || isLoadingText">
        </textarea>
      </div>

      @if (erreur) {
        <div class="error-msg">⚠️ {{ erreur }}</div>
      }

    </div>

    <!-- Les fameux DEUX boutons distincts -->
    <div class="modal-footer">
      <p class="helper-text">Choisissez comment valider cet avis :</p>
      
      <div class="action-buttons">
        
        <!-- BOUTON ÉCRIT -->
        <button class="btn-submit btn-texte" 
                (click)="soumettreTexte()" 
                [disabled]="isLoadingText || isRecording || isLoadingAudio || !commentaire">
          @if (isLoadingText) {
            <span class="spinner">⏳</span> Envoi...
          } @else {
            📝 {{ avisExistant ? 'Modifier' : 'Ajouter' }} par écrit
          }
        </button>

        <!-- BOUTON VOCAL -->
        <button class="btn-submit btn-vocal" 
                (click)="toggleEnregistrement()"
                [disabled]="isLoadingText || isLoadingAudio"
                [class.recording]="isRecording">
          @if (isLoadingAudio) {
            <span class="spinner">⏳</span> Analyse IA...
          } @else if (isRecording) {
            🛑 Stopper l'enregistrement
          } @else {
            🎤 {{ avisExistant ? 'Modifier' : 'Ajouter' }} à l'oral
          }
        </button>
        
      </div>
    </div>

  </div>
</div>

// react/agence-de-voyage-react/src/components/avis-form/AvisForm.tsx
import React, { useState, useEffect } from 'react';
import { VoyageService } from '../../services/voyage.service';
import { AudioRecorderService } from '../../services/audio-recorder.service';
import './AvisForm.css';

interface AvisFormProps {
  reservationId: number;
  avisExistant?: any;
  fermer: () => void;
  avisSoumis: () => void;
}

export const AvisFormComponent: React.FC<AvisFormProps> = ({ reservationId, avisExistant, fermer, avisSoumis }) => {
  const [note, setNote] = useState(5);
  const [commentaire, setCommentaire] = useState('');
  
  const [isLoadingText, setIsLoadingText] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [isLoadingAudio, setIsLoadingAudio] = useState(false);
  const [erreur, setErreur] = useState('');

  useEffect(() => {
    if (avisExistant) {
      setNote(avisExistant.note);
      setCommentaire(avisExistant.commentaire || '');
    }
  }, [avisExistant]);

  const soumettreTexte = () => {
    if (!commentaire.trim()) return;
    setIsLoadingText(true);
    setErreur('');

    if (avisExistant) {
      VoyageService.modifierAvis(avisExistant.id, note, commentaire)
        .then(() => {
          setIsLoadingText(false);
          avisSoumis();
        })
        .catch(() => {
          setIsLoadingText(false);
          setErreur("Erreur lors de la modification de l'avis.");
        });
    } else {
      VoyageService.creerAvisTexte(reservationId, note, commentaire)
        .then(() => {
          setIsLoadingText(false);
          avisSoumis();
        })
        .catch((err: any) => {
          setIsLoadingText(false);
          if (err.status === 409 || err.status === 400) {
            setErreur("Vous avez déjà laissé un avis pour ce voyage.");
          } else {
            setErreur("Erreur lors de l'enregistrement de l'avis.");
          }
        });
    }
  };

  const toggleEnregistrement = async () => {
    setErreur('');

    if (isRecording) {
      setIsRecording(false);
      setIsLoadingAudio(true);

      try {
        const audioBlob = await AudioRecorderService.stopRecording();
        const idPourModif = avisExistant ? avisExistant.id : undefined;
        
        VoyageService.soumettreAvisVocal(reservationId, audioBlob, note)
          .then(() => {
            setIsLoadingAudio(false);
            avisSoumis();
          })
          .catch((err: any) => {
            setIsLoadingAudio(false);
            gererErreurIA(err);
          });
      } catch (err) {
        setIsLoadingAudio(false);
        setErreur("Erreur lors de l'arrêt du micro.");
      }
    } else {
      try {
        await AudioRecorderService.startRecording();
        setIsRecording(true);
      } catch (err) {
        setErreur("L'accès au microphone a été refusé.");
      }
    }
  };

  const gererErreurIA = (err: any) => {
    if (err.status === 429) {
      setErreur("L'IA est actuellement saturée (trop de requêtes). Veuillez patienter quelques instants.");
    } else if (err.status === 503) {
      setErreur("Le service IA est temporairement indisponible.");
    } else if (err.status === 405) {
      setErreur("Action refusée. Vérifiez que la réservation est confirmée.");
    } else {
      setErreur(err.error?.error || err.error?.detail || "Une erreur est survenue lors du traitement vocal.");
    }
  };

  return (
    <div className="modal-overlay" onClick={fermer}>
      <div className="modal-content" onClick={e => e.stopPropagation()}>
        
        <div className="modal-header">
          <h3>{avisExistant ? 'Modifier mon avis' : 'Donner mon avis'}</h3>
          <button className="btn-close" onClick={fermer}>✖</button>
        </div>

        <div className="modal-body">
          <div className="rating-section">
            <p className="label">Notez votre voyage :</p>
            <div className="stars">
              {[1, 2, 3, 4, 5].map(star => (
                <span 
                  key={star} 
                  className={`star ${star <= note ? 'active' : ''}`} 
                  onClick={() => setNote(star)}
                >
                  ★
                </span>
              ))}
            </div>
          </div>

          <div className="form-group">
            <p className="label">Votre commentaire (optionnel si vocal) :</p>
            <textarea 
              value={commentaire} 
              onChange={e => setCommentaire(e.target.value)} 
              rows={4} 
              placeholder="Racontez votre expérience..."
              disabled={isRecording || isLoadingAudio || isLoadingText}
            />
          </div>

          {erreur && <div className="error-msg">⚠️ {erreur}</div>}
        </div>

        <div className="modal-footer">
          <p className="helper-text">Choisissez comment valider cet avis :</p>
          
          <div className="action-buttons">
            <button 
              className="btn-submit btn-texte" 
              onClick={soumettreTexte} 
              disabled={isLoadingText || isRecording || isLoadingAudio || !commentaire}
            >
              {isLoadingText ? (
                <><span className="spinner">⏳</span> Envoi...</>
              ) : (
                `📝 ${avisExistant ? 'Modifier' : 'Ajouter'} par écrit`
              )}
            </button>

            <button 
              className={`btn-submit btn-vocal ${isRecording ? 'recording' : ''}`} 
              onClick={toggleEnregistrement}
              disabled={isLoadingText || isLoadingAudio}
            >
              {isLoadingAudio ? (
                <><span className="spinner">⏳</span> Analyse IA...</>
              ) : isRecording ? (
                '🛑 Stopper l\'enregistrement'
              ) : (
                `🎤 ${avisExistant ? 'Modifier' : 'Ajouter'} à l'oral`
              )}
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
