// angular/agence-voyage/src/app/components/admin-dashboard/admin-dashboard.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, RouterOutlet } from '@angular/router'; // NOUVEAUX IMPORTS
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, RouterOutlet], // On importe le routeur ici
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})
export class AdminDashboardComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  // Plus de variables "ongletActif" ou de tableaux de données ici ! 

  deconnexion() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}
<div class="admin-container">
  
  <aside class="admin-sidebar">
    <div class="sidebar-header">
      <h2>🛡️ Espace Admin</h2>
    </div>

    <nav class="sidebar-nav">      
      <a routerLink="/admin/voyages" routerLinkActive="actif" class="nav-item">✈️ Liste des Voyages</a>
      <a routerLink="/admin/utilisateurs" routerLinkActive="actif" class="nav-item">👥 Liste Utilisateurs</a>
    </nav>

    <div class="sidebar-footer">
      <button class="btn-deconnexion" (click)="deconnexion()">Déconnexion</button>
    </div>
  </aside>

  <main class="admin-content">
    <router-outlet></router-outlet>
  </main>

</div>

// react/agence-de-voyage-react/src/components/admin-dashboard/AdminDashboard.tsx
import React from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { AuthService } from '../../services/auth.service';
import './AdminDashboard.css';

export const AdminDashboardComponent = () => {
  const navigate = useNavigate();

  const deconnexion = () => {
    AuthService.logout();
    navigate('/login');
  };

  return (
    <div className="admin-container">
      <aside className="admin-sidebar">
        <div className="sidebar-header">
          <h2>🛡️ Espace Admin</h2>
        </div>

        <nav className="sidebar-nav">
          <NavLink 
            to="/admin/voyages" 
            className={({ isActive }) => isActive ? "nav-item actif" : "nav-item"}
          >
            ✈️ Liste des Voyages
          </NavLink>
          <NavLink 
            to="/admin/utilisateurs" 
            className={({ isActive }) => isActive ? "nav-item actif" : "nav-item"}
          >
            👥 Liste Utilisateurs
          </NavLink>
        </nav>

        <div className="sidebar-footer">
          <button className="btn-deconnexion" onClick={deconnexion}>Déconnexion</button>
        </div>
      </aside>

      <main className="admin-content">
        {/* L'équivalent de <router-outlet></router-outlet> */}
        <Outlet />
      </main>
    </div>
  );
};
