// react/agence-de-voyage-react/src/components/profil/Profil.tsx
import React, { useState, useEffect } from 'react';
import { AuthService } from '../../services/auth.service';
import { apiFetch } from '../../interceptors/jwt.interceptor';
import './Profil.css';

export const ProfilComponent = () => {
  const idActuel = AuthService.getUserId();
  const [monProfil, setMonProfil] = useState({ email: '', motDePasse: '' });
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [hidePassword, setHidePassword] = useState(true);

  const togglePasswordVisibility = () => {
    setHidePassword(!hidePassword);
  };

  const getUrl = (): string => {
    const baseUrl = AuthService.getBaseUrl();
    const isDjango = baseUrl.includes('8000');
    return `${baseUrl}/utilisateurs/${idActuel}${isDjango ? '/' : ''}`;
  };

  const chargerMonProfil = () => {
    setIsLoading(true);
    apiFetch(getUrl())
      .then(res => {
        if (!res.ok) throw res;
        return res.json();
      })
      .then(data => {
        setMonProfil({ email: data.email, motDePasse: '' });
        setIsLoading(false);
      })
      .catch(() => {
        setMessage("❌ Impossible de charger vos informations.");
        setIsLoading(false);
      });
  };

  useEffect(() => {
    chargerMonProfil();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const sauvegarder = () => {
    setIsLoading(true);
    setMessage('');
    
    const payload: any = { email: monProfil.email };
    if (monProfil.motDePasse && monProfil.motDePasse.trim() !== '') {
       payload.motDePasse = monProfil.motDePasse;
    }

    apiFetch(getUrl(), {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    })
      .then(res => {
        if (!res.ok) throw res;
        setMessage("✅ Profil mis à jour !");
        setIsLoading(false);
        setMonProfil(prev => ({ ...prev, motDePasse: '' }));
      })
      .catch(() => {
        setMessage("❌ Erreur lors de la mise à jour.");
        setIsLoading(false);
      });
  };

  return (
    <div className="profil-container">
      <h2>👤 Mon Profil</h2>
      <p className="subtitle">Gérez vos informations personnelles (ID: {idActuel})</p>

      {isLoading && !message && (
        <div style={{ textAlign: 'center', margin: '20px 0' }}>
          <p>⏳ Chargement de vos données...</p>
        </div>
      )}

      {(!isLoading || message) && (
        <div className="form-card">
          {message && (
            <div className={`alert ${message.includes('✅') ? 'success' : ''}`}>
              {message}
            </div>
          )}

          <div className="form-group">
            <label>Adresse Email</label>
            <input 
              type="email" 
              value={monProfil.email} 
              onChange={e => setMonProfil({ ...monProfil, email: e.target.value })} 
              placeholder="votre@email.com" 
            />
          </div>

          <div className="form-group">
            <label>Nouveau mot de passe</label>
            <div className="password-wrapper">
              <input 
                type={hidePassword ? 'password' : 'text'} 
                value={monProfil.motDePasse} 
                onChange={e => setMonProfil({ ...monProfil, motDePasse: e.target.value })} 
                placeholder="Laissez vide pour conserver l'actuel" 
              />
              <button type="button" className="btn-eye" onClick={togglePasswordVisibility}>
                {hidePassword ? '👁️' : '🙈'}
              </button>
            </div>
          </div>

          <button className="btn-save" onClick={sauvegarder} disabled={isLoading}>
            💾 Mettre à jour mon profil
          </button>
        </div>
      )}
    </div>
  );
};

// angular/agence-voyage/src/app/components/profil/profil.component.ts
import { Component, OnInit, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-profil',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './profil.component.html',
  styleUrls: ['./profil.component.css']
})
export class ProfilComponent implements OnInit {
  private http = inject(HttpClient);
  public authService = inject(AuthService);
  private cdr = inject(ChangeDetectorRef);

  idActuel = this.authService.getUserId();
  monProfil: any = { email: '', motDePasse: '' };
  message: string = '';
  isLoading: boolean = true;
  
  // 👉 NOUVEAU : Gestion du petit oeil
  hidePassword = true; 
  togglePasswordVisibility() {
    this.hidePassword = !this.hidePassword;
  }

  ngOnInit() {
    this.chargerMonProfil();
  }

  private getUrl(): string {
    const baseUrl = this.authService.getBaseUrl(); 
    const isDjango = baseUrl.includes('8000');
    return `${baseUrl}/utilisateurs/${this.idActuel}${isDjango ? '/' : ''}`;
  }

  chargerMonProfil() {
    this.isLoading = true;
    this.http.get<any>(this.getUrl()).subscribe({
      next: (data) => {
        this.monProfil = { email: data.email, motDePasse: '' };
        this.isLoading = false;
        this.cdr.detectChanges(); 
      },
      error: (err) => {
        this.message = "❌ Impossible de charger vos informations.";
        this.isLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  sauvegarder() {
    this.isLoading = true;
    this.message = '';
    
    const payload: any = { email: this.monProfil.email };
    if (this.monProfil.motDePasse && this.monProfil.motDePasse.trim() !== '') {
       payload.motDePasse = this.monProfil.motDePasse;
    }

    this.http.patch(this.getUrl(), payload).subscribe({
      next: () => {
        this.message = "✅ Profil mis à jour !";
        this.isLoading = false;
        this.monProfil.motDePasse = ''; 
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.message = "❌ Erreur lors de la mise à jour.";
        this.isLoading = false;
        this.cdr.detectChanges();
      }
    });
  }
}
<div class="profil-container">
  <h2>👤 Mon Profil</h2>
  <p class="subtitle">Gérez vos informations personnelles (ID: {{ idActuel }})</p>

  <div *ngIf="isLoading && !message" style="text-align: center; margin: 20px 0;">
    <p>⏳ Chargement de vos données...</p>
  </div>

  <div class="form-card" *ngIf="!isLoading || message">
    
    <div *ngIf="message" class="alert" [class.success]="message.includes('✅')">{{ message }}</div>

    <div class="form-group">
      <label>Adresse Email</label>
      <input type="email" [(ngModel)]="monProfil.email" placeholder="votre@email.com">
    </div>

    <div class="form-group">
      <label>Nouveau mot de passe</label>
      <div class="password-wrapper">
        <input 
          [type]="hidePassword ? 'password' : 'text'" 
          [(ngModel)]="monProfil.motDePasse" 
          placeholder="Laissez vide pour conserver l'actuel"
        >
        <button type="button" class="btn-eye" (click)="togglePasswordVisibility()">
          {{ hidePassword ? '👁️' : '🙈' }}
        </button>
      </div>
    </div>

    <button class="btn-save" (click)="sauvegarder()" [disabled]="isLoading">
      💾 Mettre à jour mon profil
    </button>
  </div>
</div>
